"""OBFULL Single-Case Inspector V1 — chart-focus research case (UTC)."""

from __future__ import annotations

INSPECTOR_VERSION = "OBFULL_SINGLE_CASE_INSPECTOR_V1"
CONTRACT_VERSION = "1.0.0"
SCHEMA_VERSION = "single_case_inspector_v1"
PRICE_SOURCE = "BYBIT_PUBLIC_TRADES"
PRICE_POLICY = "LAST_TRADE_CARRY_WITH_SOURCE_GAP_GUARD_V1"
FULL_OB_STATUS = "FULL_OB_UNAVAILABLE"
FULL_OB_AVAILABLE = "FULL_OB_AVAILABLE"
MARKET_PROFILE_STATUS = "MARKET_PROFILE_NOT_IN_ENGINE_V1"

PRE_FOCUS_WINDOWS_S = (15, 30, 60, 300, 900, 1800)
OI_WINDOWS_S = (60, 300, 900, 1800)
AVR_WINDOWS_S = (15, 30, 60, 300)
OUTCOME_HORIZONS_S = (5, 15, 30, 60, 300, 900, 1800)
TIMELINE_HALF_S = 120
OI_MAX_AGE_SECONDS = 120

CASE_COMPLETE = "CASE_DATA_COMPLETE"
CASE_COMPLETE_OPTIONAL_MISSING = "CASE_DATA_COMPLETE_WITH_OPTIONAL_MODALITY_MISSING"
CASE_NOT_COMPLETE = "CASE_DATA_NOT_COMPLETE"

VERDICT_PASS = "OBFULL_SINGLE_CASE_INSPECTOR_V1_PASS"
VERDICT_PASS_LIMITS = "OBFULL_SINGLE_CASE_INSPECTOR_V1_PASS_WITH_LIMITS"
VERDICT_BLOCKED = "OBFULL_SINGLE_CASE_INSPECTOR_V1_BLOCKED_COVERAGE"
VERDICT_FAILED = "OBFULL_SINGLE_CASE_INSPECTOR_V1_FAILED"
