"""Six-case wall/trade reaction sample — research only."""

FORMAT_VERSION = "liquidity_pool_six_case_wall_trade_reaction_sample/v1"
KNOWN_ASK_START_TS = "2026-08-26T02:27:36Z"
MAX_POST_START_S = 300
PRE_START_S = 30
STRONG_IMPACT_BPS = 8.0
MIN_ATTACK_NOTIONAL = 10_000.0
NEAR_WALL_TICKS = 1.0
ACCEPT_SECONDS = 5

EVIDENCE_CLASSES = (
    "POOL_REJECTION_WITH_ABSORPTION_EVIDENCE",
    "POOL_REJECTION_MIXED_WALL_REACTION",
    "POOL_BREAKOUT_WITH_ACCEPTANCE",
    "WALL_CANCEL_OR_MOVE_DOMINANT",
    "WALL_NOT_MEANINGFULLY_ATTACKED",
    "WINDOW_CENSORED_ACTIVE",
    "INSUFFICIENT_DATA",
)
