"""Validation report models for Strategy Lab P4A/P4B/P4C."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from orderbook_analyse.strategy_lab.validation.diagnostics import IssueContext


class ValidationSeverity(str, Enum):
    ERROR = "error"
    WARNING = "warning"


class ValidationIssueCode(str, Enum):
    FEATURE_DUPLICATE_ALIAS = "FEATURE_DUPLICATE_ALIAS"
    FEATURE_UNKNOWN_ID = "FEATURE_UNKNOWN_ID"
    FEATURE_CONTRACT_VERSION = "FEATURE_CONTRACT_VERSION"
    FEATURE_DUPLICATE_PARAMETER = "FEATURE_DUPLICATE_PARAMETER"
    FEATURE_MISSING_PARAMETER = "FEATURE_MISSING_PARAMETER"
    FEATURE_UNKNOWN_PARAMETER = "FEATURE_UNKNOWN_PARAMETER"
    FEATURE_PARAMETER_TYPE = "FEATURE_PARAMETER_TYPE"
    FEATURE_PARAMETER_BOUNDS = "FEATURE_PARAMETER_BOUNDS"
    FEATURE_RATE_UNIT = "FEATURE_RATE_UNIT"
    FEATURE_IDENTIFIER_VALUE = "FEATURE_IDENTIFIER_VALUE"

    OPERAND_UNKNOWN_FEATURE_ALIAS = "OPERAND_UNKNOWN_FEATURE_ALIAS"
    OPERAND_UNKNOWN_FEATURE_OUTPUT = "OPERAND_UNKNOWN_FEATURE_OUTPUT"
    OPERATOR_UNKNOWN = "OPERATOR_UNKNOWN"
    OPERATOR_CONTRACT_VERSION = "OPERATOR_CONTRACT_VERSION"
    OPERATOR_SIGNATURE_MISMATCH = "OPERATOR_SIGNATURE_MISMATCH"
    OPERATOR_RESULT_NOT_BOOLEAN = "OPERATOR_RESULT_NOT_BOOLEAN"

    PLUGIN_UNKNOWN = "PLUGIN_UNKNOWN"
    PLUGIN_CONTRACT_VERSION = "PLUGIN_CONTRACT_VERSION"
    PLUGIN_KIND = "PLUGIN_KIND"
    PLUGIN_RESERVED_CONFIG_KEY = "PLUGIN_RESERVED_CONFIG_KEY"
    PLUGIN_DUPLICATE_PARAMETER = "PLUGIN_DUPLICATE_PARAMETER"
    PLUGIN_MISSING_PARAMETER = "PLUGIN_MISSING_PARAMETER"
    PLUGIN_UNKNOWN_PARAMETER = "PLUGIN_UNKNOWN_PARAMETER"
    PLUGIN_PARAMETER_TYPE = "PLUGIN_PARAMETER_TYPE"
    PLUGIN_PARAMETER_BOUNDS = "PLUGIN_PARAMETER_BOUNDS"
    PLUGIN_RATE_UNIT = "PLUGIN_RATE_UNIT"
    PLUGIN_POLICY_MISMATCH = "PLUGIN_POLICY_MISMATCH"
    PLUGIN_MODE_MISMATCH = "PLUGIN_MODE_MISMATCH"
    PLUGIN_REQUIRED_FEATURE_MISSING = "PLUGIN_REQUIRED_FEATURE_MISSING"
    PLUGIN_REQUIRED_FEATURE_MISMATCH = "PLUGIN_REQUIRED_FEATURE_MISMATCH"
    PLUGIN_DIRECTION_UNSUPPORTED = "PLUGIN_DIRECTION_UNSUPPORTED"

    COMPONENT_DUPLICATE_ID = "COMPONENT_DUPLICATE_ID"
    COMPONENT_UNKNOWN_REFERENCE = "COMPONENT_UNKNOWN_REFERENCE"
    COMPONENT_CYCLE = "COMPONENT_CYCLE"

    RULE_LONG_BUNDLE_MISSING = "RULE_LONG_BUNDLE_MISSING"
    RULE_LONG_BUNDLE_UNEXPECTED = "RULE_LONG_BUNDLE_UNEXPECTED"
    RULE_SHORT_BUNDLE_MISSING = "RULE_SHORT_BUNDLE_MISSING"
    RULE_SHORT_BUNDLE_UNEXPECTED = "RULE_SHORT_BUNDLE_UNEXPECTED"
    RULE_LONG_SIDE_MISMATCH = "RULE_LONG_SIDE_MISMATCH"
    RULE_SHORT_SIDE_MISMATCH = "RULE_SHORT_SIDE_MISMATCH"

    SM_DUPLICATE_STATE_ID = "SM_DUPLICATE_STATE_ID"
    SM_INITIAL_STATE_UNKNOWN = "SM_INITIAL_STATE_UNKNOWN"
    SM_DUPLICATE_TRANSITION_ID = "SM_DUPLICATE_TRANSITION_ID"
    SM_DUPLICATE_TIMEOUT_ID = "SM_DUPLICATE_TIMEOUT_ID"
    SM_UNKNOWN_FROM_STATE = "SM_UNKNOWN_FROM_STATE"
    SM_UNKNOWN_TO_STATE = "SM_UNKNOWN_TO_STATE"
    SM_UNKNOWN_TIMEOUT_STATE = "SM_UNKNOWN_TIMEOUT_STATE"
    SM_UNKNOWN_TIMEOUT_TARGET = "SM_UNKNOWN_TIMEOUT_TARGET"
    SM_UNREACHABLE_STATE = "SM_UNREACHABLE_STATE"
    SM_DUPLICATE_PRIORITY = "SM_DUPLICATE_PRIORITY"
    SM_DUPLICATE_RESET_EVENT = "SM_DUPLICATE_RESET_EVENT"
    SM_UNKNOWN_RESET_TARGET = "SM_UNKNOWN_RESET_TARGET"
    SM_INVALIDATION_WITH_EMISSION = "SM_INVALIDATION_WITH_EMISSION"
    SM_EMISSION_SIDE_UNSUPPORTED = "SM_EMISSION_SIDE_UNSUPPORTED"
    SM_LONG_EMISSION_MISSING = "SM_LONG_EMISSION_MISSING"
    SM_SHORT_EMISSION_MISSING = "SM_SHORT_EMISSION_MISSING"
    SM_RESET_EVENT_WITHOUT_SOURCE = "SM_RESET_EVENT_WITHOUT_SOURCE"

    DATA_DUPLICATE_REQUIREMENT_ID = "DATA_DUPLICATE_REQUIREMENT_ID"
    DATA_REQUIREMENT_MISSING = "DATA_REQUIREMENT_MISSING"
    DATA_REQUIREMENT_POLICY_MISMATCH = "DATA_REQUIREMENT_POLICY_MISMATCH"

    TIMEFRAME_SIGNAL_UNSUPPORTED = "TIMEFRAME_SIGNAL_UNSUPPORTED"
    TIMEFRAME_EXECUTION_MISMATCH = "TIMEFRAME_EXECUTION_MISMATCH"
    TIMEFRAME_EXECUTION_UNSUPPORTED = "TIMEFRAME_EXECUTION_UNSUPPORTED"

    WARMUP_BARS_BELOW_REQUIRED = "WARMUP_BARS_BELOW_REQUIRED"
    WARMUP_TIMEFRAME_MISMATCH = "WARMUP_TIMEFRAME_MISMATCH"
    WARMUP_SOURCE_PADDING_INSUFFICIENT = "WARMUP_SOURCE_PADDING_INSUFFICIENT"
    WARMUP_OUTCOME_PADDING_INSUFFICIENT = "WARMUP_OUTCOME_PADDING_INSUFFICIENT"

    ENTRY_DECISION_TIMING_MISMATCH = "ENTRY_DECISION_TIMING_MISMATCH"
    ENTRY_REFERENCE_RULE_MISMATCH = "ENTRY_REFERENCE_RULE_MISMATCH"

    EXIT_RATE_NON_POSITIVE = "EXIT_RATE_NON_POSITIVE"
    EXIT_HORIZON_NON_POSITIVE = "EXIT_HORIZON_NON_POSITIVE"

    COST_ROUNDTRIP_NEGATIVE = "COST_ROUNDTRIP_NEGATIVE"
    COST_SLIPPAGE_MODELED_UNSUPPORTED = "COST_SLIPPAGE_MODELED_UNSUPPORTED"
    COST_FUNDING_MODELED_UNSUPPORTED = "COST_FUNDING_MODELED_UNSUPPORTED"
    EXECUTION_ROUNDING_MODELED_UNSUPPORTED = "EXECUTION_ROUNDING_MODELED_UNSUPPORTED"

    PORTFOLIO_COMPOUNDING_UNSUPPORTED = "PORTFOLIO_COMPOUNDING_UNSUPPORTED"

    RESEARCH_DUPLICATE_DIMENSION_ID = "RESEARCH_DUPLICATE_DIMENSION_ID"
    RESEARCH_DUPLICATE_TARGET = "RESEARCH_DUPLICATE_TARGET"
    RESEARCH_CANDIDATES_EMPTY = "RESEARCH_CANDIDATES_EMPTY"
    RESEARCH_UNKNOWN_FEATURE_ALIAS = "RESEARCH_UNKNOWN_FEATURE_ALIAS"
    RESEARCH_UNKNOWN_FEATURE_PARAMETER = "RESEARCH_UNKNOWN_FEATURE_PARAMETER"
    RESEARCH_UNKNOWN_PLUGIN_PARAMETER = "RESEARCH_UNKNOWN_PLUGIN_PARAMETER"
    RESEARCH_UNKNOWN_EXIT_PARAMETER = "RESEARCH_UNKNOWN_EXIT_PARAMETER"
    RESEARCH_PLUGIN_TARGET_WITHOUT_PLUGIN = "RESEARCH_PLUGIN_TARGET_WITHOUT_PLUGIN"
    RESEARCH_CANDIDATE_TYPE = "RESEARCH_CANDIDATE_TYPE"
    RESEARCH_CANDIDATE_CONSTRAINT = "RESEARCH_CANDIDATE_CONSTRAINT"

    PROVENANCE_PLUGIN_REFS_MISSING = "PROVENANCE_PLUGIN_REFS_MISSING"
    PROVENANCE_PLUGIN_REFS_UNEXPECTED = "PROVENANCE_PLUGIN_REFS_UNEXPECTED"
    PROVENANCE_PLUGIN_REF_DUPLICATE = "PROVENANCE_PLUGIN_REF_DUPLICATE"
    PROVENANCE_PLUGIN_REF_UNKNOWN = "PROVENANCE_PLUGIN_REF_UNKNOWN"
    PROVENANCE_PLUGIN_REF_VERSION = "PROVENANCE_PLUGIN_REF_VERSION"
    PROVENANCE_CATALOG_VERSION_MISMATCH = "PROVENANCE_CATALOG_VERSION_MISMATCH"
    PROVENANCE_CAUSALITY_MISMATCH = "PROVENANCE_CAUSALITY_MISMATCH"
    PROVENANCE_CAUSALITY_NOT_ALLOWED = "PROVENANCE_CAUSALITY_NOT_ALLOWED"


@dataclass(frozen=True, slots=True, kw_only=True)
class ValidationIssue:
    code: ValidationIssueCode
    severity: ValidationSeverity
    path: str
    message: str
    context: IssueContext | None


@dataclass(frozen=True, slots=True, kw_only=True)
class ValidationReport:
    issues: tuple[ValidationIssue, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "issues", _sort_issues(self.issues))

    @property
    def errors(self) -> tuple[ValidationIssue, ...]:
        return tuple(
            issue
            for issue in self.issues
            if issue.severity is ValidationSeverity.ERROR
        )

    @property
    def warnings(self) -> tuple[ValidationIssue, ...]:
        return tuple(
            issue
            for issue in self.issues
            if issue.severity is ValidationSeverity.WARNING
        )

    @property
    def is_valid(self) -> bool:
        return not self.errors


class ValidationFailedError(Exception):
    """Raised when require_valid_strategy_v2_p4a encounters validation errors."""

    def __init__(self, report: ValidationReport) -> None:
        self.report = report
        super().__init__(
            f"StrategySpecV2 validation failed with {len(report.errors)} error(s)"
        )


def build_report(issues: tuple[ValidationIssue, ...]) -> ValidationReport:
    return ValidationReport(issues=_sort_issues(issues))


def _sort_issues(
    issues: tuple[ValidationIssue, ...],
) -> tuple[ValidationIssue, ...]:
    return tuple(
        sorted(
            issues,
            key=lambda issue: (
                issue.path,
                0 if issue.severity is ValidationSeverity.ERROR else 1,
                issue.code.value,
                issue.message,
            ),
        )
    )
