CREATE DATABASE IF NOT EXISTS live_forward;

CREATE TABLE IF NOT EXISTS live_forward.shadow_signals_long
(
    signal_id String,
    strategy_name LowCardinality(String),
    strategy_version LowCardinality(String),
    symbol LowCardinality(String),
    side LowCardinality(String),
    decision_time DateTime64(3, 'UTC'),
    detected_at DateTime64(3, 'UTC'),
    end_time Nullable(DateTime64(3, 'UTC')),
    signal_status LowCardinality(String),
    allowed UInt8,
    blocked UInt8,
    hypothetical UInt8,
    block_reason LowCardinality(String),
    raw_block_reason Nullable(String),
    entry_price Float64,
    initial_sl Float64,
    active_sl Float64,
    tp Float64,
    pool_id String,
    ladder24_pass Nullable(UInt8),
    m15_lower_2_age_h Nullable(Float64),
    be_trigger_pct Nullable(Float64),
    be_triggered UInt8,
    be_trigger_time Nullable(DateTime64(3, 'UTC')),
    tracking_status LowCardinality(String),
    outcome Nullable(String),
    pnl_pct Nullable(Float64),
    mae_pct Float64,
    mfe_pct Float64,
    duration_min Nullable(UInt32),
    horizon_time Nullable(DateTime64(3, 'UTC')),
    backfilled UInt8,
    backfill_source Nullable(String),
    last_processed_1m Nullable(DateTime64(3, 'UTC')),
    causality_status LowCardinality(String),
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC'),
    version UInt64
)
ENGINE = ReplacingMergeTree(version)
PARTITION BY toYYYYMM(decision_time)
ORDER BY (symbol, decision_time, signal_id)
PRIMARY KEY (symbol, decision_time);

CREATE TABLE IF NOT EXISTS live_forward.shadow_signals_short
(
    signal_id String,
    strategy_name LowCardinality(String),
    strategy_version LowCardinality(String),
    symbol LowCardinality(String),
    side LowCardinality(String),
    decision_time DateTime64(3, 'UTC'),
    detected_at DateTime64(3, 'UTC'),
    end_time Nullable(DateTime64(3, 'UTC')),
    signal_status LowCardinality(String),
    allowed UInt8,
    blocked UInt8,
    hypothetical UInt8,
    block_reason LowCardinality(String),
    raw_block_reason Nullable(String),
    entry_price Float64,
    initial_sl Float64,
    active_sl Float64,
    tp Float64,
    pool_id String,
    e1r_state Nullable(String),
    e1r_block_reason Nullable(String),
    floor_guard_state Nullable(String),
    tracking_status LowCardinality(String),
    outcome Nullable(String),
    pnl_pct Nullable(Float64),
    mae_pct Float64,
    mfe_pct Float64,
    duration_min Nullable(UInt32),
    horizon_time Nullable(DateTime64(3, 'UTC')),
    backfilled UInt8,
    backfill_source Nullable(String),
    last_processed_1m Nullable(DateTime64(3, 'UTC')),
    causality_status LowCardinality(String),
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC'),
    version UInt64
)
ENGINE = ReplacingMergeTree(version)
PARTITION BY toYYYYMM(decision_time)
ORDER BY (symbol, decision_time, signal_id)
PRIMARY KEY (symbol, decision_time);

CREATE OR REPLACE VIEW live_forward.shadow_signals_long_latest AS
SELECT
    signal_id,
    argMax(s.strategy_name, s.version) AS strategy_name,
    argMax(s.strategy_version, s.version) AS strategy_version,
    argMax(s.symbol, s.version) AS symbol,
    argMax(s.side, s.version) AS side,
    argMax(s.decision_time, s.version) AS decision_time,
    argMax(s.detected_at, s.version) AS detected_at,
    argMax(s.end_time, s.version) AS end_time,
    argMax(s.signal_status, s.version) AS signal_status,
    argMax(s.allowed, s.version) AS allowed,
    argMax(s.blocked, s.version) AS blocked,
    argMax(s.hypothetical, s.version) AS hypothetical,
    argMax(s.block_reason, s.version) AS block_reason,
    argMax(s.raw_block_reason, s.version) AS raw_block_reason,
    argMax(s.entry_price, s.version) AS entry_price,
    argMax(s.initial_sl, s.version) AS initial_sl,
    argMax(s.active_sl, s.version) AS active_sl,
    argMax(s.tp, s.version) AS tp,
    argMax(s.pool_id, s.version) AS pool_id,
    argMax(s.ladder24_pass, s.version) AS ladder24_pass,
    argMax(s.m15_lower_2_age_h, s.version) AS m15_lower_2_age_h,
    argMax(s.be_trigger_pct, s.version) AS be_trigger_pct,
    argMax(s.be_triggered, s.version) AS be_triggered,
    argMax(s.be_trigger_time, s.version) AS be_trigger_time,
    argMax(s.tracking_status, s.version) AS tracking_status,
    argMax(s.outcome, s.version) AS outcome,
    argMax(s.pnl_pct, s.version) AS pnl_pct,
    argMax(s.mae_pct, s.version) AS mae_pct,
    argMax(s.mfe_pct, s.version) AS mfe_pct,
    argMax(s.duration_min, s.version) AS duration_min,
    argMax(s.horizon_time, s.version) AS horizon_time,
    argMax(s.backfilled, s.version) AS backfilled,
    argMax(s.backfill_source, s.version) AS backfill_source,
    argMax(s.last_processed_1m, s.version) AS last_processed_1m,
    argMax(s.causality_status, s.version) AS causality_status,
    argMax(s.created_at, s.version) AS created_at,
    argMax(s.updated_at, s.version) AS updated_at,
    max(s.version) AS latest_version
FROM live_forward.shadow_signals_long AS s
GROUP BY signal_id;

CREATE OR REPLACE VIEW live_forward.shadow_signals_short_latest AS
SELECT
    signal_id,
    argMax(s.strategy_name, s.version) AS strategy_name,
    argMax(s.strategy_version, s.version) AS strategy_version,
    argMax(s.symbol, s.version) AS symbol,
    argMax(s.side, s.version) AS side,
    argMax(s.decision_time, s.version) AS decision_time,
    argMax(s.detected_at, s.version) AS detected_at,
    argMax(s.end_time, s.version) AS end_time,
    argMax(s.signal_status, s.version) AS signal_status,
    argMax(s.allowed, s.version) AS allowed,
    argMax(s.blocked, s.version) AS blocked,
    argMax(s.hypothetical, s.version) AS hypothetical,
    argMax(s.block_reason, s.version) AS block_reason,
    argMax(s.raw_block_reason, s.version) AS raw_block_reason,
    argMax(s.entry_price, s.version) AS entry_price,
    argMax(s.initial_sl, s.version) AS initial_sl,
    argMax(s.active_sl, s.version) AS active_sl,
    argMax(s.tp, s.version) AS tp,
    argMax(s.pool_id, s.version) AS pool_id,
    argMax(s.e1r_state, s.version) AS e1r_state,
    argMax(s.e1r_block_reason, s.version) AS e1r_block_reason,
    argMax(s.floor_guard_state, s.version) AS floor_guard_state,
    argMax(s.tracking_status, s.version) AS tracking_status,
    argMax(s.outcome, s.version) AS outcome,
    argMax(s.pnl_pct, s.version) AS pnl_pct,
    argMax(s.mae_pct, s.version) AS mae_pct,
    argMax(s.mfe_pct, s.version) AS mfe_pct,
    argMax(s.duration_min, s.version) AS duration_min,
    argMax(s.horizon_time, s.version) AS horizon_time,
    argMax(s.backfilled, s.version) AS backfilled,
    argMax(s.backfill_source, s.version) AS backfill_source,
    argMax(s.last_processed_1m, s.version) AS last_processed_1m,
    argMax(s.causality_status, s.version) AS causality_status,
    argMax(s.created_at, s.version) AS created_at,
    argMax(s.updated_at, s.version) AS updated_at,
    max(s.version) AS latest_version
FROM live_forward.shadow_signals_short AS s
GROUP BY signal_id;
