"""Fail-closed exclusion reason catalog."""

from __future__ import annotations

# Discovery / validity
NO_ZONE_TOUCH = "NO_ZONE_TOUCH"
NO_WALL_CANDIDATE = "NO_WALL_CANDIDATE"
NO_WALL_TOUCH = "NO_WALL_TOUCH"
BOOK_COVERAGE_GAP = "BOOK_COVERAGE_GAP"
BOOK_REPLAY_FAILED = "BOOK_REPLAY_FAILED"
ZONE_NOT_AVAILABLE_YET = "ZONE_NOT_AVAILABLE_YET"
ZONE_NOT_CLOSED_30M = "ZONE_NOT_CLOSED_30M"
OUTSIDE_ANALYSIS_WINDOW = "OUTSIDE_ANALYSIS_WINDOW"
MAX_PILOT_CLUSTERS_REACHED = "MAX_PILOT_CLUSTERS_REACHED"

# Frozen package limitations
WALL_FLOW_FROZEN_ASK_ONLY_V1 = "WALL_FLOW_FROZEN_ASK_ONLY_V1"
DEFENSE_CHAIN_INPUTS_MISSING = "DEFENSE_CHAIN_INPUTS_MISSING"
DEFENSE_CHAIN_ASK_ONLY_V1 = "DEFENSE_CHAIN_ASK_ONLY_V1"
PRICE_RESPONSE_FAILED = "PRICE_RESPONSE_FAILED"
HANDOFF_VALIDATION_FAILED = "HANDOFF_VALIDATION_FAILED"
DETECTION_UNAVAILABLE = "DETECTION_UNAVAILABLE"

# Outcome / feature hygiene
OUTCOME_CONTRACT_HASH_MISMATCH = "OUTCOME_CONTRACT_HASH_MISMATCH"
LOOKAHEAD_FEATURE_REFUSED = "LOOKAHEAD_FEATURE_REFUSED"
FORBIDDEN_CALC_INPUT = "FORBIDDEN_CALC_INPUT"

EXCLUSION_REASONS = (
    NO_ZONE_TOUCH,
    NO_WALL_CANDIDATE,
    NO_WALL_TOUCH,
    BOOK_COVERAGE_GAP,
    BOOK_REPLAY_FAILED,
    ZONE_NOT_AVAILABLE_YET,
    ZONE_NOT_CLOSED_30M,
    OUTSIDE_ANALYSIS_WINDOW,
    MAX_PILOT_CLUSTERS_REACHED,
    WALL_FLOW_FROZEN_ASK_ONLY_V1,
    DEFENSE_CHAIN_INPUTS_MISSING,
    DEFENSE_CHAIN_ASK_ONLY_V1,
    PRICE_RESPONSE_FAILED,
    HANDOFF_VALIDATION_FAILED,
    DETECTION_UNAVAILABLE,
    OUTCOME_CONTRACT_HASH_MISMATCH,
    LOOKAHEAD_FEATURE_REFUSED,
    FORBIDDEN_CALC_INPUT,
)


def exclusion_row(
    *,
    reason: str,
    subject_id: str | None = None,
    detail: str | None = None,
    stage: str | None = None,
) -> dict[str, str | None]:
    if reason not in EXCLUSION_REASONS:
        raise ValueError(f"unknown exclusion reason: {reason}")
    return {
        "exclusion_reason": reason,
        "subject_id": subject_id,
        "detail": detail,
        "stage": stage,
    }
