"""Pine export for C3.4A market structure — from central rule spec."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from research.regime_scanner.market_structure_c3_4a import (
    MarketStructureConfig,
    RESEARCH_MATRIX,
    STRUCTURE_STATE_CODE,
    build_rule_spec,
    config_hash,
    pine_rule_hash,
    python_rule_hash,
    rule_spec_hash,
)
from research.regime_scanner.trend_pine_export import build_pine_header, validate_pine_script

MAIN_PINE = "indicator_market_structure_c3_4a.pine"
VARIANT_PINES = {
    "balanced_medium": "indicator_market_structure_c3_4a_medium.pine",
    "fast_light": "indicator_market_structure_c3_4a_light.pine",
    "strict_strong": "indicator_market_structure_c3_4a_strong.pine",
}


def build_market_structure_pine(
    *,
    cfg: MarketStructureConfig | None = None,
    title: str | None = None,
) -> str:
    cfg = cfg or MarketStructureConfig.from_matrix_entry(RESEARCH_MATRIX[0])
    spec = build_rule_spec(cfg)
    cfg_h = config_hash(cfg)
    rule_h = rule_spec_hash(spec)
    assert pine_rule_hash(cfg) == rule_h

    lines = [
        *build_pine_header(title or f"C3.4A Market Structure ({cfg.variant_name})"),
        "// RESEARCH ONLY — market_structure_state == future bot structure reality",
        "// Background depends ONLY on market_structure_state.",
        f"// variant={cfg.variant_name}",
        f"// config_hash={cfg_h}",
        f"// rule_spec_hash={rule_h}",
        f"// pine_rule_hash={rule_h}",
        "// Causal swings: extremum then reversal; no future right-bar pivots.",
        "// Major structure holds until confirmed major break.",
        "",
        f"lookback = {cfg.lookback}",
        f"confirmBars = {cfg.confirm_bars}",
        f"minRevAtr = {cfg.min_reversal_atr}",
        f"majorMinRevAtr = {cfg.major_min_reversal_atr}",
        f"majorMinBars = {cfg.major_min_bars_between}",
        f"zoneAtr = {cfg.transition_zone_atr}",
        f"minBeyond = {cfg.min_close_beyond_atr}",
        f"reqCloses = {cfg.required_closes}",
        f'retestMode = "{cfg.retest_mode}"',
        f"retestTol = {cfg.retest_tolerance_atr}",
        f"retestHoldBars = {cfg.retest_hold_bars}",
        f'variantName = "{cfg.variant_name}"',
        "",
        'showLevels = input.bool(true, "Show break levels")',
        'showSwings = input.bool(true, "Show major swings")',
        'showTable = input.bool(true, "Show state table")',
        'showDebug = input.bool(true, "Show structure code")',
        "",
        "atr14 = ta.atr(14)",
        "safeAtr = math.max(atr14, 1e-12)",
        "",
        "// Causal pending extremes (no future bars).",
        "ph = ta.highest(high, lookback)[1]",
        "pl = ta.lowest(low, lookback)[1]",
        "var float pendingHigh = na",
        "var float pendingLow = na",
        "var int pendingHighBar = na",
        "var int pendingLowBar = na",
        "var float lastMajorHigh = na",
        "var float lastMajorLow = na",
        "var float lastMicroHigh = na",
        "var float lastMicroLow = na",
        "var int lastMajorHighBar = na",
        "var int lastMajorLowBar = na",
        "var int majorDir = 0",
        "var int microDir = 0",
        "var float prevMajorHigh = na",
        "var float prevMajorLow = na",
        "",
        "if not na(ph)",
        "    if na(pendingHigh) or ph >= pendingHigh",
        "        pendingHigh := ph",
        "        pendingHighBar := bar_index - 1",
        "if not na(pl)",
        "    if na(pendingLow) or pl <= pendingLow",
        "        pendingLow := pl",
        "        pendingLowBar := bar_index - 1",
        "",
        "bool newMajorHigh = false",
        "bool newMajorLow = false",
        "if not na(pendingHigh) and not na(pendingHighBar)",
        "    delayH = bar_index - pendingHighBar",
        "    revH = (pendingHigh - close) / safeAtr",
        "    if delayH >= confirmBars and revH >= minRevAtr",
        "        lastMicroHigh := pendingHigh",
        "        isMajH = revH >= majorMinRevAtr and (na(lastMajorHighBar) or bar_index - lastMajorHighBar >= majorMinBars)",
        "        if isMajH",
        "            prevMajorHigh := lastMajorHigh",
        "            lastMajorHigh := pendingHigh",
        "            lastMajorHighBar := bar_index",
        "            newMajorHigh := true",
        "        pendingHigh := na",
        "        pendingHighBar := na",
        "if not na(pendingLow) and not na(pendingLowBar)",
        "    delayL = bar_index - pendingLowBar",
        "    revL = (close - pendingLow) / safeAtr",
        "    if delayL >= confirmBars and revL >= minRevAtr",
        "        lastMicroLow := pendingLow",
        "        isMajL = revL >= majorMinRevAtr and (na(lastMajorLowBar) or bar_index - lastMajorLowBar >= majorMinBars)",
        "        if isMajL",
        "            prevMajorLow := lastMajorLow",
        "            lastMajorLow := pendingLow",
        "            lastMajorLowBar := bar_index",
        "            newMajorLow := true",
        "        pendingLow := na",
        "        pendingLowBar := na",
        "",
        "if newMajorHigh and newMajorLow == false",
        "    if not na(prevMajorHigh) and not na(lastMajorHigh)",
        "        if lastMajorHigh > prevMajorHigh",
        "            majorDir := majorDir == 0 ? 1 : majorDir",
        "        if lastMajorHigh < prevMajorHigh",
        "            majorDir := majorDir == 0 ? -1 : majorDir",
        "if not na(prevMajorHigh) and not na(lastMajorHigh) and not na(prevMajorLow) and not na(lastMajorLow)",
        "    if lastMajorHigh > prevMajorHigh and lastMajorLow > prevMajorLow",
        "        majorDir := 1",
        "    if lastMajorHigh < prevMajorHigh and lastMajorLow < prevMajorLow",
        "        majorDir := -1",
        "",
        "upBreak = lastMajorHigh",
        "downBreak = lastMajorLow",
        "distUp = na(upBreak) ? na : (upBreak - close) / safeAtr",
        "distDown = na(downBreak) ? na : (close - downBreak) / safeAtr",
        "wickUp = not na(upBreak) and high > upBreak",
        "wickDown = not na(downBreak) and low < downBreak",
        "closeUp = not na(upBreak) and close > upBreak + minBeyond * safeAtr",
        "closeDown = not na(downBreak) and close < downBreak - minBeyond * safeAtr",
        "var int upStreak = 0",
        "var int downStreak = 0",
        "upStreak := closeUp ? upStreak + 1 : 0",
        "downStreak := closeDown ? downStreak + 1 : 0",
        "confUp = upStreak >= reqCloses",
        "confDown = downStreak >= reqCloses",
        "zoneUp = not na(distUp) and distUp >= 0 and distUp <= zoneAtr and not confUp",
        "zoneDown = not na(distDown) and distDown >= 0 and distDown <= zoneAtr and not confDown",
        "zoneActive = zoneUp or zoneDown",
        "",
        'var string structState = "structure_unknown"',
        'var string prevStruct = "structure_unknown"',
        'var string reason = "init"',
        "var float retestLevel = na",
        "var int retestHold = 0",
        "var int stateAge = 0",
        "",
        "prevStruct := structState",
        "stateAge := stateAge + 1",
        "",
        'if prevStruct == "bullish_retest_pending" and not na(retestLevel)',
        "    held = low >= retestLevel - retestTol * safeAtr and close >= retestLevel - retestTol * safeAtr",
        "    failed = close < retestLevel - retestTol * safeAtr",
        "    if failed",
        '        structState := "bullish_break_failed"',
        '        reason := "bullish_retest_failed"',
        "        retestLevel := na",
        "        retestHold := 0",
        "    else if held",
        "        retestHold := retestHold + 1",
        "        if retestHold >= retestHoldBars",
        '            structState := "bullish_structure"',
        "            majorDir := 1",
        '            reason := "bullish_retest_confirmed"',
        "            retestLevel := na",
        "            retestHold := 0",
        "        else",
        '            structState := "bullish_retest_pending"',
        "    else",
        '        structState := "bullish_retest_pending"',
        'else if prevStruct == "bearish_retest_pending" and not na(retestLevel)',
        "    held = high <= retestLevel + retestTol * safeAtr and close <= retestLevel + retestTol * safeAtr",
        "    failed = close > retestLevel + retestTol * safeAtr",
        "    if failed",
        '        structState := "bearish_break_failed"',
        '        reason := "bearish_retest_failed"',
        "        retestLevel := na",
        "        retestHold := 0",
        "    else if held",
        "        retestHold := retestHold + 1",
        "        if retestHold >= retestHoldBars",
        '            structState := "bearish_structure"',
        "            majorDir := -1",
        '            reason := "bearish_retest_confirmed"',
        "            retestLevel := na",
        "            retestHold := 0",
        "        else",
        '            structState := "bearish_retest_pending"',
        "    else",
        '        structState := "bearish_retest_pending"',
        "else if majorDir == 0",
        "    if na(lastMajorHigh) and na(lastMajorLow)",
        '        structState := "structure_unknown"',
        '        reason := "awaiting_major_swings"',
        "    else",
        '        structState := "range_unclear"',
        '        reason := "unclear_major_sequence"',
        "else if majorDir < 0",
        "    if confUp",
        '        if retestMode == "retest"',
        '            structState := "bullish_retest_pending"',
        "            retestLevel := upBreak",
        "            retestHold := 0",
        '            reason := "confirmed_up_break_retest_pending"',
        '        else if retestMode == "hold"',
        '            structState := "bullish_break_confirmed"',
        "            majorDir := 1",
        '            reason := "confirmed_up_break_hold"',
        "        else",
        '            structState := "bullish_structure"',
        "            majorDir := 1",
        '            reason := "confirmed_up_break_flip"',
        "    else if closeUp or wickUp",
        '        structState := "bullish_break_attempt"',
        '        reason := "up_break_attempt_unconfirmed"',
        "    else if zoneUp",
        '        structState := "transition_blocked"',
        '        reason := "near_major_high_transition_zone"',
        "    else",
        '        structState := "bearish_structure"',
        '        reason := "hold_bearish_major"',
        "else",
        "    if confDown",
        '        if retestMode == "retest"',
        '            structState := "bearish_retest_pending"',
        "            retestLevel := downBreak",
        "            retestHold := 0",
        '            reason := "confirmed_down_break_retest_pending"',
        '        else if retestMode == "hold"',
        '            structState := "bearish_break_confirmed"',
        "            majorDir := -1",
        '            reason := "confirmed_down_break_hold"',
        "        else",
        '            structState := "bearish_structure"',
        "            majorDir := -1",
        '            reason := "confirmed_down_break_flip"',
        "    else if closeDown or wickDown",
        '        structState := "bearish_break_attempt"',
        '        reason := "down_break_attempt_unconfirmed"',
        "    else if zoneDown",
        '        structState := "transition_blocked"',
        '        reason := "near_major_low_transition_zone"',
        "    else",
        '        structState := "bullish_structure"',
        '        reason := "hold_bullish_major"',
        "",
        "if structState != prevStruct",
        "    stateAge := 1",
        "",
        'code = structState == "structure_unknown" ? 0 : structState == "range_unclear" ? 1 : structState == "bullish_structure" ? 2 : structState == "bullish_pullback" ? 3 : structState == "bullish_break_attempt" ? 4 : structState == "bullish_break_confirmed" ? 5 : structState == "bullish_retest_pending" ? 6 : structState == "bullish_break_failed" ? 7 : structState == "bearish_structure" ? -2 : structState == "bearish_pullback" ? -3 : structState == "bearish_break_attempt" ? -4 : structState == "bearish_break_confirmed" ? -5 : structState == "bearish_retest_pending" ? -6 : structState == "bearish_break_failed" ? -7 : structState == "transition_blocked" ? 9 : 0',
        "",
        "// Background ONLY from market_structure_state.",
        'bgcolor(structState == "bullish_structure" ? color.new(color.teal, 90) : na)',
        'bgcolor(structState == "bullish_pullback" ? color.new(color.teal, 94) : na)',
        'bgcolor(structState == "bearish_structure" ? color.new(color.maroon, 90) : na)',
        'bgcolor(structState == "bearish_pullback" ? color.new(color.maroon, 94) : na)',
        'bgcolor(structState == "bullish_break_attempt" or structState == "bearish_break_attempt" ? color.new(color.orange, 88) : na)',
        'bgcolor(structState == "transition_blocked" ? color.new(color.yellow, 85) : na)',
        'bgcolor(structState == "bullish_break_confirmed" ? color.new(color.lime, 85) : na)',
        'bgcolor(structState == "bearish_break_confirmed" ? color.new(color.red, 85) : na)',
        'bgcolor(structState == "range_unclear" ? color.new(color.gray, 94) : na)',
        "",
        'plot(showLevels ? upBreak : na, "Up break level", color=color.new(color.green, 0), style=plot.style_linebr)',
        'plot(showLevels ? downBreak : na, "Down break level", color=color.new(color.red, 0), style=plot.style_linebr)',
        'plotshape(showSwings and newMajorHigh, title="Major High", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny)',
        'plotshape(showSwings and newMajorLow, title="Major Low", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny)',
        'plotshape(structState == "transition_blocked", title="Transition blocked", style=shape.diamond, location=location.abovebar, color=color.orange, size=size.tiny)',
        'plotshape(confUp or confDown, title="Confirmed break", style=shape.flag, location=location.belowbar, color=color.blue, size=size.tiny)',
        'plot(showDebug ? code : na, "structure_state_code", display=display.data_window)',
        "",
        f'shortCfg = "{cfg_h[:12]}"',
        f'shortRule = "{rule_h[:12]}"',
        "var table diag = table.new(position.top_right, 2, 18, border_width=1)",
        "if showTable and barstate.islast",
        '    table.cell(diag, 0, 0, "structure")',
        "    table.cell(diag, 1, 0, structState)",
        '    table.cell(diag, 0, 1, "majorDir")',
        "    table.cell(diag, 1, 1, str.tostring(majorDir))",
        '    table.cell(diag, 0, 2, "upBreak")',
        '    table.cell(diag, 1, 2, na(upBreak) ? "-" : str.tostring(upBreak, "#.####"))',
        '    table.cell(diag, 0, 3, "downBreak")',
        '    table.cell(diag, 1, 3, na(downBreak) ? "-" : str.tostring(downBreak, "#.####"))',
        '    table.cell(diag, 0, 4, "distUpATR")',
        '    table.cell(diag, 1, 4, na(distUp) ? "-" : str.tostring(distUp, "#.###"))',
        '    table.cell(diag, 0, 5, "distDownATR")',
        '    table.cell(diag, 1, 5, na(distDown) ? "-" : str.tostring(distDown, "#.###"))',
        '    table.cell(diag, 0, 6, "zone")',
        "    table.cell(diag, 1, 6, str.tostring(zoneActive))",
        '    table.cell(diag, 0, 7, "wick/close/conf")',
        '    table.cell(diag, 1, 7, str.tostring(wickUp or wickDown) + "/" + str.tostring(closeUp or closeDown) + "/" + str.tostring(confUp or confDown))',
        '    table.cell(diag, 0, 8, "reason")',
        "    table.cell(diag, 1, 8, reason)",
        '    table.cell(diag, 0, 9, "age")',
        "    table.cell(diag, 1, 9, str.tostring(stateAge))",
        '    table.cell(diag, 0, 10, "variant")',
        "    table.cell(diag, 1, 10, variantName)",
        '    table.cell(diag, 0, 11, "config")',
        "    table.cell(diag, 1, 11, shortCfg)",
        '    table.cell(diag, 0, 12, "rule")',
        "    table.cell(diag, 1, 12, shortRule)",
        "",
        "// EOF",
    ]
    text = "\n".join(lines) + "\n"
    validate_pine_script(text)
    if re.search(r"(?m)^strategy\(", text):
        raise ValueError("market structure pine must not contain strategy(")
    return text


def write_market_structure_pines(output_dir: Path) -> dict[str, Any]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, str] = {}
    hashes: dict[str, str] = {}
    default = MarketStructureConfig.from_matrix_entry(RESEARCH_MATRIX[0])
    main = build_market_structure_pine(cfg=default)
    main_path = output_dir / MAIN_PINE
    main_path.write_text(main, encoding="utf-8")
    paths["main"] = str(main_path)
    hashes["main"] = hashlib.sha256(main.encode()).hexdigest()

    for entry in RESEARCH_MATRIX:
        name = str(entry["name"])
        if name not in VARIANT_PINES:
            continue
        cfg = MarketStructureConfig.from_matrix_entry(entry)
        text = build_market_structure_pine(cfg=cfg)
        path = output_dir / VARIANT_PINES[name]
        path.write_text(text, encoding="utf-8")
        paths[name] = str(path)
        hashes[name] = hashlib.sha256(text.encode()).hexdigest()

    return {
        "paths": paths,
        "content_hashes": hashes,
        "config_hash": config_hash(default),
        "rule_spec_hash": rule_spec_hash(cfg=default),
        "pine_rule_hash": pine_rule_hash(default),
        "python_rule_hash": python_rule_hash(default),
        "state_codes": dict(STRUCTURE_STATE_CODE),
    }
