"""Pine export for C3.4B protected market structure — from central rule spec."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from research.regime_scanner.market_structure_c3_4b import (
    RESEARCH_MATRIX,
    PROTECTED_STATE_CODE,
    ProtectedStructureConfig,
    build_rule_spec,
    config_hash,
    pine_rule_hash,
    python_rule_hash,
    rule_spec_hash,
)
from research.regime_scanner.trend_pine_export import build_pine_header, validate_pine_script

MAIN_PINE = "indicator_market_structure_c3_4b_protected.pine"
VARIANT_PINES = {
    "protected_medium": "indicator_market_structure_c3_4b_protected_medium.pine",
    "protected_fast": "indicator_market_structure_c3_4b_protected_light.pine",
    "protected_strict": "indicator_market_structure_c3_4b_protected_strong.pine",
}


def build_protected_structure_pine(
    *,
    cfg: ProtectedStructureConfig | None = None,
    title: str | None = None,
) -> str:
    cfg = cfg or ProtectedStructureConfig.from_matrix_entry(RESEARCH_MATRIX[0])
    spec = build_rule_spec(cfg)
    cfg_h = config_hash(cfg)
    rule_h = rule_spec_hash(spec)
    assert pine_rule_hash(cfg) == rule_h

    lines = [
        *build_pine_header(title or f"C3.4B Protected Structure ({cfg.variant_name})"),
        "// RESEARCH ONLY — protected_structure_state kept internally; bgcolor STRICTLY from majorDir.",
        "// transition_blocked is rising-edge marker only (never tints bgcolor).",
        "// Markers are rising-edge only. Candidate latch: replace only if structurally better.",
        f"// variant={cfg.variant_name}",
        f"// config_hash={cfg_h}",
        f"// rule_spec_hash={rule_h}",
        f"// pine_rule_hash={rule_h}",
        "// Micro extremes use ta.highestbars/lowestbars (true source bar). micro_min_bars_between enforced.",
        "",
        f"lookback = {cfg.lookback}",
        f"confirmBars = {cfg.confirm_bars}",
        f"minRevAtr = {cfg.min_reversal_atr}",
        f"microMinBars = {cfg.micro_min_bars_between}",
        f"zoneAtr = {cfg.transition_zone_atr}",
        f"minBeyond = {cfg.min_close_beyond_atr}",
        f"reqCloses = {cfg.required_closes}",
        f'chochMode = "{cfg.choch_mode}"',
        f"chochHoldBars = {cfg.choch_hold_bars}",
        f"retestTol = {cfg.retest_tolerance_atr}",
        f'variantName = "{cfg.variant_name}"',
        "",
        'showProtected = input.bool(true, "Show protected levels")',
        'showBothProtectedLevels = input.bool(false, "Show both historical protected levels")',
        'showCandidates = input.bool(false, "Show candidate protected")',
        'showMicro = input.bool(false, "Show micro swings")',
        'showMicroDebug = input.bool(false, "Show micro / source-bar debug")',
        'showTable = input.bool(true, "Show state table")',
        'showDebug = input.bool(false, "Show structure debug (data window)")',
        "",
        "atr14 = ta.atr(14)",
        "safeAtr = math.max(atr14, 1e-12)",
        "",
        "// True extreme within lookback ending at previous bar (exclude current forming bar).",
        "hb = ta.highestbars(high, lookback)[1]",
        "lb = ta.lowestbars(low, lookback)[1]",
        "ph = ta.highest(high, lookback)[1]",
        "pl = ta.lowest(low, lookback)[1]",
        "// highestbars/lowestbars return 0 or negative offset relative to the [1] bar.",
        "// Absolute source uses addition: (bar_index - 1) + hb  (hb is <= 0).",
        "extHighBar = not na(hb) ? (bar_index - 1 + hb) : na",
        "extLowBar = not na(lb) ? (bar_index - 1 + lb) : na",
        "validHighSource = not na(extHighBar) and extHighBar <= bar_index - 1 and extHighBar >= bar_index - lookback",
        "validLowSource = not na(extLowBar) and extLowBar <= bar_index - 1 and extLowBar >= bar_index - lookback",
        "",
        "var float pendingHigh = na",
        "var float pendingLow = na",
        "var int pendingHighBar = na",
        "var int pendingLowBar = na",
        "var int lastConfHighSrc = na",
        "var int lastConfLowSrc = na",
        "var int lastMicroHighConfBar = na",
        "var int lastMicroLowConfBar = na",
        "var float lastMicroHigh = na",
        "var float lastMicroLow = na",
        "var float protectedHigh = na",
        "var float protectedLow = na",
        "var float candHigh = na",
        "var float candLow = na",
        'var string candLeg = "none"',
        "var float lastExtHigh = na",
        "var float lastExtLow = na",
        "var int majorDir = 0",
        "var int prevMajorDir = 0",
        "var int upStreak = 0",
        "var int downStreak = 0",
        "var int chochHold = 0",
        'var string structState = "structure_unknown"',
        'var string prevStruct = "structure_unknown"',
        'var string reason = "init"',
        "var int stateAge = 0",
        "var bool newMicroHigh = false",
        "var bool newMicroLow = false",
        "",
        "newMicroHigh := false",
        "newMicroLow := false",
        "",
        "// Arm pending from causal rolling extreme (skip already-confirmed / invalid source bars).",
        "if not na(ph) and validHighSource",
        "    alreadyH = not na(lastConfHighSrc) and extHighBar == lastConfHighSrc",
        "    if not alreadyH",
        "        if na(pendingHigh) or extHighBar != pendingHighBar or ph >= pendingHigh",
        "            pendingHigh := ph",
        "            pendingHighBar := extHighBar",
        "if not na(pl) and validLowSource",
        "    alreadyL = not na(lastConfLowSrc) and extLowBar == lastConfLowSrc",
        "    if not alreadyL",
        "        if na(pendingLow) or extLowBar != pendingLowBar or pl <= pendingLow",
        "            pendingLow := pl",
        "            pendingLowBar := extLowBar",
        "",
        "if not na(pendingHigh) and not na(pendingHighBar)",
        "    delayH = bar_index - pendingHighBar",
        "    revH = (pendingHigh - close) / safeAtr",
        "    if delayH >= confirmBars and revH >= minRevAtr",
        "        if not na(lastConfHighSrc) and pendingHighBar == lastConfHighSrc",
        "            pendingHigh := na",
        "            pendingHighBar := na",
        "        else if not na(lastMicroHighConfBar) and bar_index - lastMicroHighConfBar < microMinBars",
        "            pendingHigh := na",
        "            pendingHighBar := na",
        "        else",
        "            lastMicroHigh := pendingHigh",
        "            lastMicroHighConfBar := bar_index",
        "            lastConfHighSrc := pendingHighBar",
        "            newMicroHigh := true",
        "            // Seed protected high only when major unknown/bearish (active side).",
        "            if na(protectedHigh) and majorDir <= 0",
        "                protectedHigh := pendingHigh",
        "                lastExtHigh := pendingHigh",
        "            else if majorDir < 0",
        "                // Candidate latch: first or strictly higher only.",
        '                if candLeg != "high" or na(candHigh) or pendingHigh > candHigh',
        "                    candHigh := pendingHigh",
        '                    candLeg := "high"',
        "            pendingHigh := na",
        "            pendingHighBar := na",
        "",
        "if not na(pendingLow) and not na(pendingLowBar)",
        "    delayL = bar_index - pendingLowBar",
        "    revL = (close - pendingLow) / safeAtr",
        "    if delayL >= confirmBars and revL >= minRevAtr",
        "        if not na(lastConfLowSrc) and pendingLowBar == lastConfLowSrc",
        "            pendingLow := na",
        "            pendingLowBar := na",
        "        else if not na(lastMicroLowConfBar) and bar_index - lastMicroLowConfBar < microMinBars",
        "            pendingLow := na",
        "            pendingLowBar := na",
        "        else",
        "            lastMicroLow := pendingLow",
        "            lastMicroLowConfBar := bar_index",
        "            lastConfLowSrc := pendingLowBar",
        "            newMicroLow := true",
        "            // Seed protected low only when major unknown/bullish (active side).",
        "            if na(protectedLow) and majorDir >= 0",
        "                protectedLow := pendingLow",
        "                lastExtLow := pendingLow",
        "            else if majorDir > 0",
        '                if candLeg != "low" or na(candLow) or pendingLow < candLow',
        "                    candLow := pendingLow",
        '                    candLeg := "low"',
        "            pendingLow := na",
        "            pendingLowBar := na",
        "",
        "// Invalidate mismatched candidate legs.",
        'if majorDir >= 0 and candLeg == "high"',
        "    candHigh := na",
        '    candLeg := "none"',
        'if majorDir <= 0 and candLeg == "low"',
        "    candLow := na",
        '    candLeg := "none"',
        "",
        "// Continuation promotes latched candidate -> protected.",
        "if majorDir < 0 and newMicroLow and not na(candHigh)",
        "    isLL = na(lastExtLow) or lastMicroLow < lastExtLow",
        "    if isLL",
        "        protectedHigh := candHigh",
        "        lastExtLow := lastMicroLow",
        "        candHigh := na",
        '        candLeg := "none"',
        "if majorDir > 0 and newMicroHigh and not na(candLow)",
        "    isHH = na(lastExtHigh) or lastMicroHigh > lastExtHigh",
        "    if isHH",
        "        protectedLow := candLow",
        "        lastExtHigh := lastMicroHigh",
        "        candLow := na",
        '        candLeg := "none"',
        "",
        "extLevel = majorDir < 0 ? protectedHigh : majorDir > 0 ? protectedLow : na",
        "distExt = na(extLevel) ? na : majorDir < 0 ? (extLevel - close) / safeAtr : (close - extLevel) / safeAtr",
        "wickUp = not na(protectedHigh) and high > protectedHigh",
        "wickDown = not na(protectedLow) and low < protectedLow",
        "closeUp = not na(protectedHigh) and close > protectedHigh + minBeyond * safeAtr",
        "closeDown = not na(protectedLow) and close < protectedLow - minBeyond * safeAtr",
        "upStreak := closeUp ? upStreak + 1 : 0",
        "downStreak := closeDown ? downStreak + 1 : 0",
        "extUp = majorDir < 0 and upStreak >= reqCloses",
        "extDown = majorDir > 0 and downStreak >= reqCloses",
        "intUp = not na(lastMicroHigh) and close > lastMicroHigh and (na(protectedHigh) or close <= protectedHigh)",
        "intDown = not na(lastMicroLow) and close < lastMicroLow and (na(protectedLow) or close >= protectedLow)",
        "zoneActive = not na(distExt) and distExt >= 0 and distExt <= zoneAtr and not extUp and not extDown",
        "",
        "prevStruct := structState",
        "stateAge := stateAge + 1",
        "",
        'if prevStruct == "bullish_choch" or prevStruct == "bullish_structure_candidate"',
        "    held = not na(protectedHigh) and close >= protectedHigh - retestTol * safeAtr",
        "    failed = not na(protectedHigh) and close < protectedHigh - retestTol * safeAtr and not closeUp",
        "    if failed and wickUp and not closeUp",
        '        structState := "bullish_break_failed"',
        "        majorDir := -1",
        '        reason := "bullish_choch_failed"',
        "        chochHold := 0",
        '    else if chochMode == "immediate"',
        '        structState := "bullish_structure"',
        "        majorDir := 1",
        '        reason := "choch_immediate"',
        '    else if chochMode == "hold"',
        "        if held",
        "            chochHold := chochHold + 1",
        "            if chochHold >= chochHoldBars",
        '                structState := "bullish_structure"',
        "                majorDir := 1",
        '                reason := "choch_hold_confirm"',
        "                chochHold := 0",
        "            else",
        '                structState := "bullish_structure_candidate"',
        '                reason := "choch_holding"',
        "        else",
        '            structState := "bullish_choch"',
        "            chochHold := 0",
        "    else",
        '        structState := "bullish_structure_candidate"',
        '        reason := "choch_await_confirm"',
        'else if prevStruct == "bearish_choch" or prevStruct == "bearish_structure_candidate"',
        "    held = not na(protectedLow) and close <= protectedLow + retestTol * safeAtr",
        "    failed = not na(protectedLow) and close > protectedLow + retestTol * safeAtr and not closeDown",
        "    if failed and wickDown and not closeDown",
        '        structState := "bearish_break_failed"',
        "        majorDir := 1",
        '        reason := "bearish_choch_failed"',
        "        chochHold := 0",
        '    else if chochMode == "immediate"',
        '        structState := "bearish_structure"',
        "        majorDir := -1",
        '        reason := "choch_immediate"',
        '    else if chochMode == "hold"',
        "        if held",
        "            chochHold := chochHold + 1",
        "            if chochHold >= chochHoldBars",
        '                structState := "bearish_structure"',
        "                majorDir := -1",
        '                reason := "choch_hold_confirm"',
        "                chochHold := 0",
        "            else",
        '                structState := "bearish_structure_candidate"',
        '                reason := "choch_holding"',
        "        else",
        '            structState := "bearish_choch"',
        "            chochHold := 0",
        "    else",
        '        structState := "bearish_structure_candidate"',
        '        reason := "choch_await_confirm"',
        "else if majorDir == 0",
        "    if na(protectedHigh) and na(protectedLow)",
        '        structState := "structure_unknown"',
        '        reason := "awaiting_levels"',
        "    else",
        '        structState := "range_unclear"',
        '        reason := "unclear"',
        "    if not na(lastExtHigh) and not na(lastExtLow) and not na(lastMicroHigh) and not na(lastMicroLow)",
        "        if lastMicroHigh < lastExtHigh and lastMicroLow < lastExtLow",
        "            majorDir := -1",
        "        if lastMicroHigh > lastExtHigh and lastMicroLow > lastExtLow",
        "            majorDir := 1",
        "else if majorDir < 0",
        "    if extUp",
        '        if chochMode == "immediate"',
        '            structState := "bullish_structure"',
        "            majorDir := 1",
        '            reason := "external_bos_immediate"',
        "        else",
        '            structState := "bullish_choch"',
        '            reason := "external_bos_up"',
        "            chochHold := 0",
        "    else if zoneActive",
        '        structState := "transition_blocked"',
        '        reason := "near_protected_high"',
        "    else if intUp",
        '        structState := "bullish_internal_break"',
        '        reason := "internal_bos_up"',
        "    else",
        '        structState := "bearish_structure"',
        '        reason := "hold_bearish_protected"',
        "else",
        "    if extDown",
        '        if chochMode == "immediate"',
        '            structState := "bearish_structure"',
        "            majorDir := -1",
        '            reason := "external_bos_immediate"',
        "        else",
        '            structState := "bearish_choch"',
        '            reason := "external_bos_down"',
        "            chochHold := 0",
        "    else if zoneActive",
        '        structState := "transition_blocked"',
        '        reason := "near_protected_low"',
        "    else if intDown",
        '        structState := "bearish_internal_break"',
        '        reason := "internal_bos_down"',
        "    else",
        '        structState := "bullish_structure"',
        '        reason := "hold_bullish_protected"',
        "",
        "if structState != prevStruct",
        "    stateAge := 1",
        "",
        "// Drop inactive opposite protected level on majorDir change (no crossed residue).",
        "if majorDir != prevMajorDir",
        "    if majorDir < 0",
        "        protectedLow := na",
        "        candLow := na",
        '        if candLeg == "low"',
        '            candLeg := "none"',
        "        if na(protectedHigh) and not na(lastMicroHigh)",
        "            protectedHigh := lastMicroHigh",
        "            lastExtHigh := lastMicroHigh",
        "    if majorDir > 0",
        "        protectedHigh := na",
        "        candHigh := na",
        '        if candLeg == "high"',
        '            candLeg := "none"',
        "        if na(protectedLow) and not na(lastMicroLow)",
        "            protectedLow := lastMicroLow",
        "            lastExtLow := lastMicroLow",
        "    prevMajorDir := majorDir",
        "",
        "// Safety: never keep crossed pair while a major side is active.",
        "if majorDir < 0 and not na(protectedHigh) and not na(protectedLow) and protectedHigh <= protectedLow",
        "    protectedLow := na",
        "if majorDir > 0 and not na(protectedHigh) and not na(protectedLow) and protectedHigh <= protectedLow",
        "    protectedHigh := na",
        "",
        'code = structState == "structure_unknown" ? 0 : structState == "range_unclear" ? 1 : structState == "bullish_structure" ? 2 : structState == "bullish_pullback" ? 3 : structState == "bullish_internal_break" ? 4 : structState == "bullish_choch" ? 5 : structState == "bullish_structure_candidate" ? 6 : structState == "bullish_retest_pending" ? 7 : structState == "bullish_break_failed" ? 8 : structState == "bearish_structure" ? -2 : structState == "bearish_pullback" ? -3 : structState == "bearish_internal_break" ? -4 : structState == "bearish_choch" ? -5 : structState == "bearish_structure_candidate" ? -6 : structState == "bearish_retest_pending" ? -7 : structState == "bearish_break_failed" ? -8 : structState == "transition_blocked" ? 9 : 0',
        "",
        "// Background STRICTLY from majorDir only (bullish / bearish / neutral).",
        "// transition_blocked is marker-only and must not tint bgcolor.",
        "bgBull = majorDir > 0",
        "bgBear = majorDir < 0",
        "bgcolor(bgBull ? color.new(color.teal, 90) : bgBear ? color.new(color.maroon, 90) : na)",
        "",
        "// Rising-edge markers only.",
        "extBosActive = extUp or extDown",
        "extBosEntry = extBosActive and not extBosActive[1]",
        "intBosActive = intUp or intDown",
        "intBosEntry = intBosActive and not intBosActive[1]",
        'chochActive = structState == "bullish_choch" or structState == "bearish_choch"',
        "chochEntry = chochActive and not chochActive[1]",
        'zoneBlockedActive = structState == "transition_blocked"',
        "zoneBlockedEntry = zoneBlockedActive and not zoneBlockedActive[1]",
        "",
        "// Default: only active external level. Optional: both historical sides (no cross-side join).",
        "showHigh = showProtected and (showBothProtectedLevels or majorDir < 0)",
        "showLow = showProtected and (showBothProtectedLevels or majorDir > 0)",
        'plot(showHigh ? protectedHigh : na, "Protected High", color=color.new(color.red, 0), linewidth=2, style=plot.style_linebr)',
        'plot(showLow ? protectedLow : na, "Protected Low", color=color.new(color.green, 0), linewidth=2, style=plot.style_linebr)',
        'plot(showCandidates ? candHigh : na, "Candidate Protected High", color=color.new(color.orange, 30), style=plot.style_linebr)',
        'plot(showCandidates ? candLow : na, "Candidate Protected Low", color=color.new(color.aqua, 30), style=plot.style_linebr)',
        'plot(showMicro ? lastMicroHigh : na, "Micro High", color=color.new(color.gray, 50), style=plot.style_circles)',
        'plot(showMicro ? lastMicroLow : na, "Micro Low", color=color.new(color.gray, 50), style=plot.style_circles)',
        'plotshape(extBosEntry, title="External BOS", style=shape.flag, location=location.belowbar, color=color.blue, size=size.tiny)',
        'plotshape(chochEntry, title="CHoCH", style=shape.diamond, location=location.abovebar, color=color.orange, size=size.tiny)',
        'plotshape(zoneBlockedEntry, title="Transition blocked", style=shape.xcross, location=location.abovebar, color=color.yellow, size=size.tiny)',
        'plotshape(intBosEntry, title="Internal BOS", style=shape.circle, location=location.belowbar, color=color.gray, size=size.tiny)',
        'plot(showDebug ? code : na, "protected_state_code", display=display.data_window)',
        'plot(showDebug ? majorDir : na, "major_direction", display=display.data_window)',
        'plot(showDebug ? stateAge : na, "structure_state_age", display=display.data_window)',
        'plot(showDebug ? distExt : na, "distance_to_external_atr", display=display.data_window)',
        'plot(showMicroDebug ? hb : na, "highestbars_offset", display=display.data_window)',
        'plot(showMicroDebug ? lb : na, "lowestbars_offset", display=display.data_window)',
        'plot(showMicroDebug ? extHighBar : na, "ext_high_source_bar", display=display.data_window)',
        'plot(showMicroDebug ? extLowBar : na, "ext_low_source_bar", display=display.data_window)',
        'plot(showMicroDebug ? pendingHighBar : na, "pending_high_source_bar", display=display.data_window)',
        'plot(showMicroDebug ? pendingLowBar : na, "pending_low_source_bar", display=display.data_window)',
        "",
        f'shortCfg = "{cfg_h[:12]}"',
        f'shortRule = "{rule_h[:12]}"',
        "activeExt = majorDir < 0 ? protectedHigh : majorDir > 0 ? protectedLow : na",
        "var table diag = table.new(position.top_right, 2, 18, border_width=1)",
        "if showTable and barstate.islast",
        '    table.cell(diag, 0, 0, "protected")',
        "    table.cell(diag, 1, 0, structState)",
        '    table.cell(diag, 0, 1, "majorDir")',
        "    table.cell(diag, 1, 1, str.tostring(majorDir))",
        '    table.cell(diag, 0, 2, "activeExt")',
        '    table.cell(diag, 1, 2, na(activeExt) ? "-" : str.tostring(activeExt, "#.####"))',
        '    table.cell(diag, 0, 3, "protHigh/Low")',
        '    table.cell(diag, 1, 3, (na(protectedHigh) ? "-" : str.tostring(protectedHigh, "#.####")) + "/" + (na(protectedLow) ? "-" : str.tostring(protectedLow, "#.####")))',
        '    table.cell(diag, 0, 4, "candHigh/Low")',
        '    table.cell(diag, 1, 4, (na(candHigh) ? "-" : str.tostring(candHigh, "#.####")) + "/" + (na(candLow) ? "-" : str.tostring(candLow, "#.####")))',
        '    table.cell(diag, 0, 5, "candLeg")',
        "    table.cell(diag, 1, 5, candLeg)",
        '    table.cell(diag, 0, 6, "extLevel")',
        '    table.cell(diag, 1, 6, na(extLevel) ? "-" : str.tostring(extLevel, "#.####"))',
        '    table.cell(diag, 0, 7, "distExtATR")',
        '    table.cell(diag, 1, 7, na(distExt) ? "-" : str.tostring(distExt, "#.###"))',
        '    table.cell(diag, 0, 8, "zone")',
        "    table.cell(diag, 1, 8, str.tostring(zoneActive))",
        '    table.cell(diag, 0, 9, "reason")',
        "    table.cell(diag, 1, 9, reason)",
        '    table.cell(diag, 0, 10, "age")',
        "    table.cell(diag, 1, 10, str.tostring(stateAge))",
        '    table.cell(diag, 0, 11, "variant")',
        "    table.cell(diag, 1, 11, variantName)",
        '    table.cell(diag, 0, 12, "config")',
        "    table.cell(diag, 1, 12, shortCfg)",
        '    table.cell(diag, 0, 13, "rule")',
        "    table.cell(diag, 1, 13, shortRule)",
        "",
        "// EOF",
    ]
    text = "\n".join(lines) + "\n"
    validate_pine_script(text)
    if re.search(r"(?m)^strategy\(", text):
        raise ValueError("protected structure pine must not contain strategy(")
    return text


def write_protected_structure_pines(output_dir: Path) -> dict[str, Any]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, str] = {}
    hashes: dict[str, str] = {}
    default = ProtectedStructureConfig.from_matrix_entry(RESEARCH_MATRIX[0])
    main = build_protected_structure_pine(cfg=default)
    main_path = output_dir / MAIN_PINE
    main_path.write_text(main, encoding="utf-8")
    paths["main"] = str(main_path)
    hashes["main"] = hashlib.sha256(main.encode()).hexdigest()

    for entry in RESEARCH_MATRIX:
        name = str(entry["name"])
        if name not in VARIANT_PINES:
            continue
        cfg = ProtectedStructureConfig.from_matrix_entry(entry)
        text = build_protected_structure_pine(cfg=cfg)
        path = output_dir / VARIANT_PINES[name]
        path.write_text(text, encoding="utf-8")
        paths[name] = str(path)
        hashes[name] = hashlib.sha256(text.encode()).hexdigest()

    return {
        "paths": paths,
        "content_hashes": hashes,
        "config_hash": config_hash(default),
        "rule_spec_hash": rule_spec_hash(cfg=default),
        "pine_rule_hash": pine_rule_hash(default),
        "python_rule_hash": python_rule_hash(default),
        "state_codes": dict(PROTECTED_STATE_CODE),
    }
