"""Idempotent Phase-2 DDL, strictly confined to the frozen database."""

from __future__ import annotations

from .contracts import TARGET_DATABASE, assert_target_database


def _table(name: str, columns: str, order_by: str, partition: str = "") -> str:
    partition_sql = f"\nPARTITION BY {partition}" if partition else ""
    return f"""CREATE TABLE IF NOT EXISTS {TARGET_DATABASE}.{name}
(
{columns}
)
ENGINE = MergeTree{partition_sql}
ORDER BY {order_by}"""


COMMON = """
    contract_version LowCardinality(String),
    source_semantics_version LowCardinality(String),
    build_id FixedString(64),
    coverage_status LowCardinality(String),
    computed_at DateTime64(6, 'UTC')
""".strip()


def statements() -> list[str]:
    assert_target_database(TARGET_DATABASE)
    trade_columns = f"""
    symbol LowCardinality(String),
    bucket_start DateTime64(3, 'UTC'),
    buy_base_volume Decimal(30, 12),
    sell_base_volume Decimal(30, 12),
    buy_quote_notional Decimal(30, 8),
    sell_quote_notional Decimal(30, 8),
    taker_delta_quote_notional Decimal(30, 8),
    buy_trade_count UInt32,
    sell_trade_count UInt32,
    first_trade_ts DateTime64(3, 'UTC'),
    last_trade_ts DateTime64(3, 'UTC'),
    source_trade_count UInt32,
    deduplicated_trade_count UInt32,
    {COMMON}
"""
    return [
        _table(
            "research_schema_versions",
            """    contract_version LowCardinality(String),
    schema_fingerprint FixedString(64),
    build_id FixedString(64),
    applied_at DateTime64(6, 'UTC'),
    status LowCardinality(String)""",
            "(contract_version, build_id)",
        ),
        _table(
            "research_producer_lineage",
            """    symbol LowCardinality(String),
    producer_id LowCardinality(String),
    producer_type LowCardinality(String),
    source_path_or_table String,
    source_semantics LowCardinality(String),
    event_time_available UInt8,
    receive_time_available UInt8,
    reconstruction_clock LowCardinality(String),
    coverage_start DateTime64(6, 'UTC'),
    coverage_end DateTime64(6, 'UTC'),
    terminal_reason LowCardinality(String),
    coverage_complete UInt8,
    transition_contract String,
    source_fingerprint FixedString(64),
    contract_version LowCardinality(String),
    build_id FixedString(64),
    recorded_at DateTime64(6, 'UTC')""",
            "(symbol, producer_id, build_id)",
        ),
        _table(
            "research_batch_runs",
            """    batch_id String,
    build_id FixedString(64),
    contract_version LowCardinality(String),
    pilot_start DateTime64(3, 'UTC'),
    pilot_end DateTime64(3, 'UTC'),
    status LowCardinality(String),
    phase LowCardinality(String),
    input_fingerprint FixedString(64),
    output_fingerprint FixedString(64),
    rows_written UInt64,
    started_at DateTime64(6, 'UTC'),
    completed_at Nullable(DateTime64(6, 'UTC')),
    error String""",
            "(batch_id, status, phase)",
        ),
        _table(
            "research_data_quality_events",
            """    event_key FixedString(64),
    symbol LowCardinality(String),
    event_time DateTime64(3, 'UTC'),
    quality_type LowCardinality(String),
    severity LowCardinality(String),
    details String,
    source_id LowCardinality(String),
    contract_version LowCardinality(String),
    build_id FixedString(64),
    recorded_at DateTime64(6, 'UTC')""",
            "(quality_type, symbol, event_time, event_key)",
        ),
        _table(
            "research_public_trade_buckets_100ms",
            trade_columns,
            "(symbol, bucket_start, build_id)",
            "(symbol, toYYYYMMDD(bucket_start))",
        ),
        _table(
            "research_public_trade_buckets_500ms",
            trade_columns,
            "(symbol, bucket_start, build_id)",
            "(symbol, toYYYYMMDD(bucket_start))",
        ),
        _table(
            "research_public_trade_buckets_1s",
            trade_columns,
            "(symbol, bucket_start, build_id)",
            "(symbol, toYYYYMMDD(bucket_start))",
        ),
        _table(
            "research_liquidation_buckets_500ms",
            f"""    symbol LowCardinality(String),
    bucket_start DateTime64(3, 'UTC'),
    liquidated_long_count UInt32,
    liquidated_short_count UInt32,
    forced_buy_base Decimal(30, 12),
    forced_sell_base Decimal(30, 12),
    bankruptcy_reference_notional Decimal(30, 8),
    event_count UInt32,
    {COMMON}""",
            "(symbol, bucket_start, build_id)",
            "(symbol, toYYYYMMDD(bucket_start))",
        ),
        _table(
            "research_open_interest_observations",
            f"""    symbol LowCardinality(String),
    observation_time DateTime64(3, 'UTC'),
    open_interest Decimal(30, 12),
    open_interest_value Decimal(30, 8),
    source_event_time DateTime64(3, 'UTC'),
    state_age_ms UInt64,
    state_valid UInt8,
    original_frequency_ms UInt32,
    source_unit LowCardinality(String),
    {COMMON}""",
            "(symbol, observation_time, build_id)",
            "(symbol, toYYYYMMDD(observation_time))",
        ),
        _table(
            "research_tpo_bracket_ranges_30m",
            f"""    symbol LowCardinality(String),
    session_id String,
    bracket_index UInt16,
    bracket_start DateTime64(3, 'UTC'),
    bracket_end DateTime64(3, 'UTC'),
    low Nullable(Decimal(18, 8)),
    high Nullable(Decimal(18, 8)),
    low_bin Nullable(Int64),
    high_bin Nullable(Int64),
    touched_bin_count UInt32,
    trade_count UInt32,
    trade_size_used_as_weight UInt8,
    {COMMON}""",
            "(symbol, session_id, bracket_index, build_id)",
        ),
        _table(
            "research_tpo_profile_bins_session",
            f"""    symbol LowCardinality(String),
    session_id String,
    price_bin_index Int64,
    price_bin_tick Int64,
    display_price Decimal(18, 8),
    tpo_count UInt32,
    tpo_share Float64,
    bracket_count UInt32,
    is_poc UInt8,
    is_value_area UInt8,
    {COMMON}""",
            "(symbol, session_id, price_bin_index, build_id)",
        ),
        _table(
            "research_volume_profile_bins_session",
            f"""    symbol LowCardinality(String),
    session_id String,
    price_bin_index Int64,
    price_bin_tick Int64,
    price_bin_low Decimal(18, 8),
    price_bin_high Decimal(18, 8),
    display_price Decimal(18, 8),
    base_volume Decimal(30, 12),
    quote_notional Decimal(30, 8),
    trade_count UInt64,
    taker_buy_base_volume Decimal(30, 12),
    taker_sell_base_volume Decimal(30, 12),
    {COMMON}""",
            "(symbol, session_id, price_bin_index, build_id)",
        ),
        _table(
            "research_profile_levels_session",
            f"""    symbol LowCardinality(String),
    session_id String,
    profile_kind LowCardinality(String),
    level_kind LowCardinality(String),
    price Decimal(18, 8),
    value_area_share Float64,
    {COMMON}""",
            "(symbol, session_id, profile_kind, level_kind, build_id)",
        ),
        _table(
            "research_ob200_snapshots_1s",
            f"""    symbol LowCardinality(String),
    snapshot_ts DateTime64(0, 'UTC'),
    producer_id LowCardinality(String),
    bid_price_ticks Array(Int64) CODEC(Delta, ZSTD(5)),
    bid_quantities Array(Decimal(24, 12)) CODEC(ZSTD(5)),
    ask_price_ticks Array(Int64) CODEC(Delta, ZSTD(5)),
    ask_quantities Array(Decimal(24, 12)) CODEC(ZSTD(5)),
    best_bid Decimal(18, 8),
    best_ask Decimal(18, 8),
    mid Decimal(18, 8),
    spread Decimal(18, 8),
    bid_level_count UInt16,
    ask_level_count UInt16,
    genuine_depth UInt8,
    reconstruction_clock LowCardinality(String),
    source_event_count UInt32,
    source_event_time DateTime64(3, 'UTC'),
    source_update_id UInt64,
    ordering_quality LowCardinality(String),
    source_fingerprint FixedString(64),
    {COMMON}""",
            "(symbol, snapshot_ts, producer_id, contract_version, build_id)",
            "(symbol, toYYYYMMDD(snapshot_ts))",
        ),
    ]
