"""Constants for research 1m Stoch entry-timing variants."""

from __future__ import annotations

VARIANT_BASELINE_IMMEDIATE = "BASELINE_IMMEDIATE"
VARIANT_WAIT_1M_EXTREME = "WAIT_1M_EXTREME"
VARIANT_WAIT_1M_EXTREME_TURN_SLOPE = "WAIT_1M_EXTREME_TURN_SLOPE"
VARIANT_WAIT_1M_EXTREME_TURN_CROSS = "WAIT_1M_EXTREME_TURN_CROSS"

TIMING_VARIANTS: tuple[str, ...] = (
    VARIANT_BASELINE_IMMEDIATE,
    VARIANT_WAIT_1M_EXTREME,
    VARIANT_WAIT_1M_EXTREME_TURN_SLOPE,
    VARIANT_WAIT_1M_EXTREME_TURN_CROSS,
)

# Default for research dashboard display (not production).
DEFAULT_RESEARCH_DISPLAY_VARIANT = VARIANT_WAIT_1M_EXTREME_TURN_CROSS

TRIGGER_WAITING_FOR_1M_EXTREME = "WAITING_FOR_1M_EXTREME"
TRIGGER_WAITING_FOR_1M_TURN = "WAITING_FOR_1M_TURN"
TRIGGER_ENTRY_TRIGGERED = "ENTRY_TRIGGERED"
TRIGGER_NO_ENTRY_TIMEOUT = "NO_ENTRY_TIMEOUT"

# Dashboard-facing labels for variant selector (no Baseline as active source).
DASHBOARD_VARIANT_CHOICES: tuple[tuple[str, str], ...] = (
    (VARIANT_WAIT_1M_EXTREME, "Extreme"),
    (VARIANT_WAIT_1M_EXTREME_TURN_SLOPE, "Turn Slope"),
    (VARIANT_WAIT_1M_EXTREME_TURN_CROSS, "Turn Cross"),
)
