"""L2 Wall-to-Wall Strategy Discovery V1."""

FORMAT_VERSION = "l2_wall_to_wall_discovery/v1"

HORIZONS_S = (300, 900, 1800, 3600, 14400)  # 5m..4h
COST_BPS = (0, 11, 15, 20)
NOTIONAL_USDT = 1000.0
FRONT_RUN_BPS = 2.0
BREAK_DISTANCE_BPS = 1.5
RECLAIM_VARIANTS = ("R1_CROSS", "R2_HOLD_1S", "R3_HOLD_3S", "R4_RETEST_HOLD", "R5_REFILL_RECLAIM")
BREAK_VARIANTS = ("B1_HOLD_1S", "B2_HOLD_3S", "B3_DISTANCE_CONFIRM", "B4_RETEST_FAIL", "B5_WALL_REMOVED_CONFIRM")
EXIT_VARIANTS = (
    "E1_TARGET_FIRST_TOUCH",
    "E2_FRONT_RUN_TARGET",
    "E3_TARGET_DEFENSE_CONFIRM",
    "E4_TARGET_BREAK_CONTINUE",
    "E5_TARGET_BREAK_RECLAIM_EXIT",
    "E6_INVALIDATION_EXIT",
)
