"""BOUNDED_LEVEL_FIRST_ANALYZER_PILOT_V1 — causal level-first research only."""

from __future__ import annotations

CONTRACT_NAME = "BOUNDED_LEVEL_FIRST_ANALYZER_PILOT_V1"
CONTRACT_VERSION = "1.1.0"
SCHEMA_VERSION = "bounded_level_first_analyzer_pilot_v1"
PHASE2_CONTRACT = "MARKET_PROFILE_LLD_SHARED_EVENT_MATERIALIZATION_V1"
PHASE2_RUN_KEY = "rk_cc609a0004ebf336"
PHASE2_CONFIG_HASH = "a5902c9f3222c745da504b1a43678ca53d776829fa158a174147acdada77b6dc"
PHASE2_MP_CONFIG_HASH = "956368d8bf54e54c52e3937cfd96581295a8b068c3db0800b8e1fa6844807f4a"
PHASE2_LLD_CONFIG_HASH = "fccab56a2494844a476b8eb6dbb2885dd85366cf5c203d67932b5b26c2932961"

DEFAULT_SYMBOL = "BTCUSDT"
DEFAULT_START_Z = "2026-09-06T19:00:00Z"
DEFAULT_END_Z = "2026-09-06T23:00:00Z"
DEFAULT_OUTCOME_END_Z = "2026-09-06T23:30:00Z"

MP_TIMEFRAMES = ("30m", "1h", "4h")
TF_RANK = {"30m": 1, "1h": 2, "4h": 3}
VISIBLE_TPO_TYPES = ("TPO_POC", "TPO_VAH", "TPO_VAL")
LLD_SOURCE_TIMEFRAME = "15m"

CLOSED_LEVEL_TYPES = (
    "CLOSED_30M_TPO_POC",
    "CLOSED_30M_TPO_VAH",
    "CLOSED_30M_TPO_VAL",
    "CLOSED_1H_TPO_POC",
    "CLOSED_1H_TPO_VAH",
    "CLOSED_1H_TPO_VAL",
    "CLOSED_4H_TPO_POC",
    "CLOSED_4H_TPO_VAH",
    "CLOSED_4H_TPO_VAL",
)
DEVELOPING_LEVEL_TYPES = (
    "DEVELOPING_30M_TPO_POC",
    "DEVELOPING_30M_TPO_VAH",
    "DEVELOPING_30M_TPO_VAL",
    "DEVELOPING_1H_TPO_POC",
    "DEVELOPING_1H_TPO_VAH",
    "DEVELOPING_1H_TPO_VAL",
    "DEVELOPING_4H_TPO_POC",
    "DEVELOPING_4H_TPO_VAH",
    "DEVELOPING_4H_TPO_VAL",
)

CONFLUENCE_CLASSES = (
    "SINGLE_30M",
    "SINGLE_1H",
    "SINGLE_4H",
    "MULTI_TF_30M_1H",
    "MULTI_TF_30M_4H",
    "MULTI_TF_1H_4H",
    "MULTI_TF_30M_1H_4H",
    "MIXED_CLOSED_DEVELOPING",
)

LLD_CONFLUENCE_TYPES = (
    "MP_ONLY",
    "MP_WITH_LLD_RESISTANCE",
    "MP_WITH_LLD_SUPPORT",
    "MP_WITH_MULTIPLE_LLD",
    "MP_LLD_DIRECTION_CONFLICT",
)

EPISODE_STATUSES = (
    "LEVEL_AVAILABLE",
    "FIRST_APPROACH",
    "FIRST_TOUCH",
    "INSIDE_LEVEL_ZONE",
    "LEFT_LEVEL_ZONE_UP",
    "LEFT_LEVEL_ZONE_DOWN",
    "RETURNED_TO_LEVEL",
    "INVALIDATED_BY_DATA_QUALITY",
    "EPISODE_CLOSED",
)

REACTION_CLASSES = (
    "TOUCH_UNRESOLVED",
    "REJECTED_DOWN_FROM_RESISTANCE_CONTEXT",
    "REJECTED_UP_FROM_SUPPORT_CONTEXT",
    "BROKE_UP",
    "BROKE_DOWN",
    "RECLAIMED_UP",
    "RECLAIMED_DOWN",
    "ACCEPTED_ABOVE",
    "ACCEPTED_BELOW",
    "CHOPPED_AROUND_LEVEL",
    "DATA_NOT_COMPLETE",
)

BEARISH_REACTIONS = (
    "REJECTED_DOWN_FROM_RESISTANCE_CONTEXT",
    "RECLAIMED_DOWN",
    "ACCEPTED_BELOW",
)
BULLISH_REACTIONS = (
    "REJECTED_UP_FROM_SUPPORT_CONTEXT",
    "RECLAIMED_UP",
    "ACCEPTED_ABOVE",
)

REACTION_HORIZON_S = 900
EVIDENCE_PRE_TOUCH_S = 300
HORIZONS_S = (5, 15, 30, 60, 300, 900, 1800)
MARK_PCTS = (0.05, 0.10, 0.20, 0.30, 0.50)
FIRST_MOVE_FLOOR_PCT = 0.01
INSUFFICIENT_SAMPLE_N = 5

FORBIDDEN_SOURCES = (
    "all_liquidations",
    "binance_liquidation_heatmap",
    "screenshot",
    "png_pixel",
    "naked_poc",
    "volume_vah_as_tpo",
    "profile_high_as_tpo_vah",
)
FORBIDDEN_LABELS = (
    "SHORT_LIQUIDATION_POOL",
    "LONG_LIQUIDATION_POOL",
    "LIQUIDATED",
    "CONSUMED",
    "PARTIALLY_CONSUMED",
    "liquidation_notional",
    "notional_usdt",
)

FROZEN_HC_RUN = "results/high_conviction_aligned_filter_v1/BTCUSDT/two_windows/hcv1_62ffdd8f3e439a9b"
FROZEN_PHASE2_DIR = (
    "results/market_profile_lld_shared_event_materialization_v1/BTCUSDT/rk_cc609a0004ebf336"
)
FROZEN_PHASE1_DIR = "results/market_profile_liquidation_chart_source_parity_audit_v1"

from .runner import run_pilot  # noqa: E402

__all__ = [
    "CONTRACT_NAME",
    "CONTRACT_VERSION",
    "PHASE2_RUN_KEY",
    "run_pilot",
]
