"""Write the Phase-3 final report. Descriptive only."""

from __future__ import annotations

from typing import Any

from ..analyze.run_key import atomic_write_text
from .persist import now_z
from .summarize import count_values


def write_report(
    *,
    directory,
    verdict: str,
    cfg: dict[str, Any],
    coverage: dict[str, Any],
    mp_snapshots: list[dict[str, Any]],
    lld_snapshots: list[dict[str, Any]],
    levels: list[dict[str, Any]],
    clusters: list[dict[str, Any]],
    episodes: list[dict[str, Any]],
    reactions: list[dict[str, Any]],
    analyzers: list[dict[str, Any]],
    confluence: list[dict[str, Any]],
    path_rows: list[dict[str, Any]],
    summary: list[dict[str, Any]],
    quality: list[dict[str, Any]],
    cache: Any,
    elapsed_s: float,
    rss_mb: float,
    flags: dict[str, Any],
    blind_hash: str,
    trade_meta: dict[str, Any],
    mid_meta: dict[str, Any],
    candle_meta: dict[str, Any],
) -> None:
    directed = [r for r in reactions if r.get("reaction_direction") in {"BULLISH", "BEARISH"}]
    lines = [
        "# BOUNDED_LEVEL_FIRST_ANALYZER_PILOT_V1",
        "",
        f"Verdict: **{verdict}**",
        "",
        f"- written_at: {now_z()}",
        f"- run_key: `{directory.name}`",
        f"- window: `{cfg['start']}` → `{cfg['end']}` outcome through `{cfg['outcome_end']}`",
        f"- phase2_run_key: `{cfg['phase2_run_key']}`",
        f"- mp_config_hash: `{cfg['mp_config_hash']}`",
        f"- lld_config_hash: `{cfg['lld_config_hash']}`",
        f"- detection_blind_hash: `{blind_hash}`",
        f"- clickhouse_writes: 0",
        f"- runtime_s: {elapsed_s:.2f}",
        f"- rss_mb: {rss_mb:.1f}",
        "",
        "## Coverage",
        "",
        f"- verdict: `{coverage.get('verdict')}`",
        f"- interval: `{((coverage.get('interval_coverage') or {}).get('verdict'))}`",
        f"- localized: `{((coverage.get('localized_coverage') or {}).get('verdict'))}`",
        "",
        "## Counts",
        "",
        f"- MP snapshots: {len(mp_snapshots)} (generator calls={cache.mp_calls}, reused={cache.mp_reused})",
        f"- LLD snapshots: {len(lld_snapshots)} (generator calls={cache.lld_calls}, reused={cache.lld_reused})",
        f"- MP levels: {len(levels)}",
        f"- level clusters: {len(clusters)}",
        f"- touch episodes: {len(episodes)}",
        f"- directed reactions: {len(directed)} / {len(reactions)}",
        f"- quality exclusions: {len(quality)}",
        "",
        "### CLOSED / DEVELOPING levels",
        "",
        f"- {count_values(levels, 'profile_state')}",
        "",
        "### Timeframes",
        "",
        f"- {count_values(levels, 'timeframe')}",
        "",
        "### TPO types",
        "",
        f"- {count_values(levels, 'tpo_type')}",
        "",
        "### LLD confluence",
        "",
        f"- {count_values(confluence, 'lld_confluence_type')}",
        "",
        "### Reactions",
        "",
        f"- {count_values(reactions, 'reaction_class')}",
        "",
        "### Analyzer labels",
        "",
        f"- Full-OB: {count_values(analyzers, 'full_ob_label')}",
        f"- Footprint: {count_values(analyzers, 'footprint_label')}",
        f"- OI: {count_values(analyzers, 'oi_label')}",
        "",
        "## Outcome blindness",
        "",
        f"- outcomes_loaded_before_level_events: {flags['outcomes_loaded_before_level_events']}",
        f"- outcomes_loaded_before_reaction_classification: {flags['outcomes_loaded_before_reaction_classification']}",
        f"- outcomes_loaded_before_detection_hash: {flags['outcomes_loaded_before_detection_hash']}",
        "",
        "## Path outcomes (descriptive)",
        "",
        f"- path rows: {len(path_rows)}",
        f"- group rows: {len(summary)}",
        "- no significance or profitability claim",
        "",
        "## Inputs",
        "",
        f"- trades: {trade_meta}",
        f"- 1s mid: {mid_meta}",
        f"- 1m candles: {candle_meta}",
        "",
        "## Limits",
        "",
        "- Shared-generator parity is inherited from Phase 2; historical rendered chart GET parity is still not proven.",
        "- Break is not acceptance. Reactions are not entries.",
        "- LLD strength is normalized volume, not USDT notional.",
        "",
    ]
    atomic_write_text(directory / "final_report.md", "\n".join(lines) + "\n")
