"""OBFULL_AVR_MULTISCALE_FOOTPRINT_CONTEXT_V1 — causal multi-window episode context."""

from __future__ import annotations

ADAPTER_VERSION = "OBFULL_AVR_MULTISCALE_FOOTPRINT_CONTEXT_V1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_SCHEMA = "avr_multiscale_episode_context_v1"
FOOTPRINT_5M_SCHEMA = "footprint_5m_context_v1"
JOIN_VERSION = "OI_LIQ_JOIN_FROM_MB_STATE_1S_V1"
WINDOWS_S = (15, 30, 60, 300)
CANDLE_5M_S = 300
OI_MAX_AGE_SECONDS = 120
LOOKBACK_S = 300  # public trades / state lookback before feature start

VERDICT_PASS = "OBFULL_AVR_MULTISCALE_FOOTPRINT_CONTEXT_V1_PASS"
VERDICT_PASS_AVR_LIMITS = "OBFULL_AVR_MULTISCALE_FOOTPRINT_CONTEXT_V1_PASS_WITH_AVR_QUALITY_LIMITS"
VERDICT_BLOCKED_COVERAGE = "OBFULL_AVR_MULTISCALE_BLOCKED_COVERAGE"
VERDICT_BLOCKED_PARITY = "OBFULL_AVR_MULTISCALE_BLOCKED_BY_5M_PARITY_MISMATCH"
VERDICT_FAILED = "OBFULL_AVR_MULTISCALE_FAILED"
