"""OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1 — offline end-to-end wiring."""

from __future__ import annotations

ORCHESTRATOR_VERSION = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1"
ORCHESTRATOR_CONTRACT = "1.0.0"
MAX_OUTCOME_HORIZON_SECONDS = 1800
STAGES = (
    "PRECHECK",
    "STATE_PREPARE",
    "CANDIDATE_DETECT",
    "EPISODE_GROUP",
    "PUBLIC_TRADE_OUTCOMES",
    "VALIDATE",
    "UNIFIED_TECHNICAL_REPORT",
)

STAGES_WITH_AVR = (
    "PRECHECK",
    "STATE_PREPARE",
    "CANDIDATE_DETECT",
    "EPISODE_GROUP",
    "AVR_CONTEXT",
    "PUBLIC_TRADE_OUTCOMES",
    "VALIDATE",
    "UNIFIED_TECHNICAL_REPORT",
)

STAGES_WITH_AVR_MULTISCALE = (
    "PRECHECK",
    "STATE_PREPARE",
    "CANDIDATE_DETECT",
    "EPISODE_GROUP",
    "AVR_CONTEXT",
    "AVR_MULTISCALE_CONTEXT",
    "PUBLIC_TRADE_OUTCOMES",
    "VALIDATE",
    "UNIFIED_TECHNICAL_REPORT",
)


def stages_for(*, with_avr: bool = False, with_avr_multiscale: bool = False) -> tuple[str, ...]:
    if with_avr_multiscale:
        return STAGES_WITH_AVR_MULTISCALE
    if with_avr:
        return STAGES_WITH_AVR
    return STAGES

EXIT_OK = 0
EXIT_DATA_NOT_COMPLETE = 2
EXIT_USAGE = 64
EXIT_INTERNAL = 70

VERDICT_PASS = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1_PASS"
VERDICT_PASS_REFERENCED = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1_PASS_WITH_REFERENCED_ARTIFACTS"
VERDICT_BLOCKED_COVERAGE = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1_BLOCKED_COVERAGE"
VERDICT_FAILED = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1_FAILED"
VERDICT_SKIPPED = "OBFULL_RESEARCH_ANALYZE_ORCHESTRATOR_V1_SKIPPED_ALREADY_COMPLETE"
