"""Causal Liquidity Location pool lifecycle event-study (research-only)."""

from __future__ import annotations

ANALYSIS_ID = "LIQUIDITY_LOCATION_POOL_LIFECYCLE_ANALYSIS"
ANALYSIS_VERSION = "v1"
EXPECTED_SMOKE_VERDICT = "LIQUIDITY_LOCATION_POOL_LIFECYCLE_SMOKE_COMPLETE"
CAUSALITY_BLOCKED_VERDICT = "LIQUIDITY_LOCATION_CAUSALITY_BLOCKED"

__all__ = [
    "ANALYSIS_ID",
    "ANALYSIS_VERSION",
    "EXPECTED_SMOKE_VERDICT",
    "CAUSALITY_BLOCKED_VERDICT",
]
