"""full_ob_cache_bridge_protocol_v1 — constants and status codes (anchor_retention_v2 semantics)."""

from __future__ import annotations

from typing import Final

PROTOCOL_VERSION: Final = "full_ob_cache_bridge_protocol_v1"
PROTOCOL_MAJOR: Final = 1
CONTRACT_ID: Final = "full_ob_cache_bridge_anchor_retention_v2"

STATUS_DATA_COMPLETE: Final = "DATA_COMPLETE"
STATUS_BRIDGE_DISABLED: Final = "BRIDGE_DISABLED"
STATUS_SYMBOL_NOT_ALLOWED: Final = "SYMBOL_NOT_ALLOWED"
STATUS_BUFFER_NOT_WARM: Final = "BUFFER_NOT_WARM"
STATUS_PRE_ROLL_TOO_SHORT: Final = "PRE_ROLL_TOO_SHORT"
STATUS_BOOK_ANCHOR_MISSING: Final = "BOOK_ANCHOR_MISSING"
STATUS_SEQUENCE_GAP: Final = "SEQUENCE_GAP"
STATUS_DELTA_CONTINUITY_GAP: Final = "DELTA_CONTINUITY_GAP"
STATUS_BUFFER_OVERFLOW: Final = "BUFFER_OVERFLOW"
STATUS_RECONNECT_IN_WINDOW: Final = "RECONNECT_IN_WINDOW"
STATUS_RESYNC_CHECKPOINT_MISSING: Final = "RESYNC_CHECKPOINT_MISSING"
STATUS_STARTUP_PRE_ROLL_INCOMPLETE: Final = "STARTUP_PRE_ROLL_INCOMPLETE"
STATUS_ANCHOR_EPOCH_MISMATCH: Final = "ANCHOR_EPOCH_MISMATCH"
STATUS_BOOK_HASH_MISMATCH: Final = "BOOK_HASH_MISMATCH"
STATUS_DATA_STALE: Final = "DATA_STALE"
STATUS_PAYLOAD_TOO_LARGE: Final = "PAYLOAD_TOO_LARGE"
STATUS_PAYLOAD_LIMIT_EXCEEDED: Final = "PAYLOAD_LIMIT_EXCEEDED"
STATUS_REQUEST_BUSY: Final = "REQUEST_BUSY"
STATUS_FREEZE_CONCURRENCY_LIMIT: Final = "FREEZE_CONCURRENCY_LIMIT"
STATUS_REQUEST_TIMEOUT: Final = "REQUEST_TIMEOUT"
STATUS_INTERNAL_ERROR: Final = "INTERNAL_ERROR"
STATUS_PROTOCOL_MISMATCH: Final = "PROTOCOL_MISMATCH"
STATUS_INVALID_REQUEST: Final = "INVALID_REQUEST"

KNOWN_STATUS_CODES: Final = frozenset(
    {
        STATUS_DATA_COMPLETE,
        STATUS_BRIDGE_DISABLED,
        STATUS_SYMBOL_NOT_ALLOWED,
        STATUS_BUFFER_NOT_WARM,
        STATUS_PRE_ROLL_TOO_SHORT,
        STATUS_BOOK_ANCHOR_MISSING,
        STATUS_SEQUENCE_GAP,
        STATUS_DELTA_CONTINUITY_GAP,
        STATUS_BUFFER_OVERFLOW,
        STATUS_RECONNECT_IN_WINDOW,
        STATUS_RESYNC_CHECKPOINT_MISSING,
        STATUS_STARTUP_PRE_ROLL_INCOMPLETE,
        STATUS_ANCHOR_EPOCH_MISMATCH,
        STATUS_BOOK_HASH_MISMATCH,
        STATUS_DATA_STALE,
        STATUS_PAYLOAD_TOO_LARGE,
        STATUS_PAYLOAD_LIMIT_EXCEEDED,
        STATUS_REQUEST_BUSY,
        STATUS_FREEZE_CONCURRENCY_LIMIT,
        STATUS_REQUEST_TIMEOUT,
        STATUS_INTERNAL_ERROR,
        STATUS_PROTOCOL_MISMATCH,
        STATUS_INVALID_REQUEST,
    }
)

OP_STATUS: Final = "status"
OP_FREEZE_PRE_ROLL: Final = "freeze_pre_roll"

REPLAY_CAPABILITY_RAW_FULL_BOOK: Final = "RAW_FULL_BOOK_REPLAY"
REPLAY_CAPABILITY_NONE: Final = "NONE"

ANCHOR_TYPE_PERIODIC_BOOK_CHECKPOINT: Final = "PERIODIC_BOOK_CHECKPOINT"
ANCHOR_TYPE_INITIAL_CHECKPOINT: Final = "INITIAL_CHECKPOINT"
ANCHOR_TYPE_RESYNC_CHECKPOINT: Final = "RESYNC_CHECKPOINT"
ANCHOR_TYPE_MISSING: Final = "MISSING"

CHECKPOINT_KIND_INITIAL: Final = "INITIAL_CHECKPOINT"
CHECKPOINT_KIND_PERIODIC: Final = "PERIODIC_BOOK_CHECKPOINT"
CHECKPOINT_KIND_RESYNC: Final = "RESYNC_CHECKPOINT"
