"""Feature specification document (definitions + signs; no optimized thresholds)."""

from __future__ import annotations

FEATURE_SPECIFICATION: dict = {
    "schema_version": 1,
    "causality": {
        "rule": "Only data with timestamp <= decision_at; signal bar must be fully closed.",
        "no_entry_path": "Entry bar and post-decision 8h path never used as features.",
        "no_outcomes": "MFE/MAE/exit/TP/SL/PnL never used as features; labels appended separately.",
        "missing_policy": "null + coverage_status; never substitute 0 or NEUTRAL.",
    },
    "reference_strategy": {
        "timeframe": "5m",
        "mode": "M0_STRICT_SYNC",
        "group": "CORE_RESEARCH_SUPPORTIVE",
        "tp_pct": 0.75,
        "sl_pct": 0.50,
        "horizon": "8h",
        "cost_pct": 0.15,
        "entry_rule": "SIGNAL_TF_NEXT_OPEN_AFTER_SIGNAL_BAR",
        "exclude": [],
    },
    "mirroring": {
        "long": "Positive bid support / buy flow remains positive.",
        "short": "Ask support / sell flow is sign-flipped so trade-supportive is positive.",
        "formula": "directional = raw * (+1 LONG | -1 SHORT)",
    },
    "features": {
        "close_at_decision": "Close of last completed 5m bar at decision_at.",
        "atr14_abs": "14-bar rolling mean of True Range on completed 5m bars.",
        "atr14_pct": "atr14_abs / close * 100; null if atr<=0 or close<=0.",
        "signal_bar_range_pct": "(high-low)/close*100 of signal bar.",
        "signal_bar_body_pct": "abs(close-open)/close*100 of signal bar.",
        "signal_bar_range_atr": "(high-low)/atr14_abs.",
        "rolling_range_1h_pct": "(max high - min low) over last 12 completed 5m bars / close * 100.",
        "rolling_range_4h_pct": "Same over 48 bars.",
        "realized_volatility_1h": "std(log returns)*sqrt(n) over 12 closes.",
        "realized_volatility_4h": "Same over 48 closes.",
        "tp_pct": "Constant 0.75.",
        "sl_pct": "Constant 0.50.",
        "tp_atr_ratio": "0.75 / atr14_pct; null if atr14_pct invalid.",
        "sl_atr_ratio": "0.50 / atr14_pct; null if atr14_pct invalid.",
        "reward_risk_gross": "0.75/0.50.",
        "net_tp_pct": "0.75-0.15.",
        "net_sl_pct": "0.50+0.15.",
        "ema9": "SMA-seed EMA(9) on completed closes.",
        "ema20": "EMA(20).",
        "ema59": "EMA(59).",
        "ema*_slope_1bar_pct": "(ema_t - ema_{t-1}) / close * 100.",
        "ema*_slope_atr": "(ema_t - ema_{t-1}) / atr14_abs.",
        "ema9_20_distance_pct": "(ema9-ema20)/close*100 signed.",
        "ema9_20_distance_atr": "(ema9-ema20)/atr14_abs signed.",
        "ema_stack_direction": "+1 if ema9&ema20>ema59; -1 if both <; else 0.",
        "ema_stack_aligned_with_trade": "+1 if stack matches direction; -1 opposite; 0 if stack=0.",
        "ema59_slope_aligned_with_trade": "sign(ema59_slope)*direction_sign.",
        "fast_ema_cohesion": "abs(ema9-ema20)/atr14_abs (smaller = tighter).",
        "return_*_pct": "(close - close_n_bars_ago)/close_n_bars_ago*100.",
        "efficiency_ratio_*": "|net close move| / sum(|bar close moves|).",
        "close_position_in_*_range": "(close-low)/(high-low) in window.",
        "atr_short_long_ratio": "ATR14 / ATR56.",
        "ob_imbalance_*": "From orderbook_features_1s_v2; l20/impact NOT_AVAILABLE.",
        "ob_imbalance_directional": "mirror(imbalance_l50_last).",
        "directional_flow_*": "mirror(buy_notional - sell_notional).",
        "flow_acceleration": "directional_1m - (directional_5m - directional_1m)/4.",
        "lld_*": "Always null with CAUSALITY_UNPROVEN unless proven causal pools supplied.",
    },
    "labels": {
        "prefix": "label__",
        "fields": [
            "exit_reason",
            "exit_at",
            "duration_minutes",
            "gross_return_pct",
            "net_return_pct",
            "net_pnl_usdt",
            "net_win",
            "tp_exit",
            "sl_exit",
            "time_exit",
        ],
        "note": "Copied from checkpoint trades; never recomputed; never enter feature functions.",
    },
    "hypotheses": {
        "H1": "Within SUPPORTIVE, non-neutral trade-confirming OB vs neutral OB.",
        "H2": "ATR% and TP/ATR, SL/ATR expectancy across global research-sample quartiles.",
        "H3": "EMA59 slope/ATR and EMA9-20 distance/ATR vs profitable/unprofitable.",
        "H4": "trade_flow_verdict=CONFIRMING vs not.",
        "forbidden": "No threshold search, no combinatorial filters, no in-sample best filter pick.",
    },
}
