"""OBFULL_FOOTPRINT_AVR_EPISODE_CONTEXT_ADAPTER_V1."""

from __future__ import annotations

ADAPTER_VERSION = "OBFULL_FOOTPRINT_AVR_EPISODE_CONTEXT_ADAPTER_V1"
ADAPTER_CONTRACT = "1.0.0"

VERDICT_PASS = "OBFULL_FOOTPRINT_AVR_EPISODE_CONTEXT_ADAPTER_V1_PASS"
VERDICT_PASS_MISSING = "OBFULL_FOOTPRINT_AVR_EPISODE_CONTEXT_ADAPTER_V1_PASS_WITH_VALID_MISSING_CONTEXT"
VERDICT_PARITY_BLOCK = "OBFULL_FOOTPRINT_AVR_ADAPTER_BLOCKED_BY_PARITY_MISMATCH"
VERDICT_BLOCKED = "OBFULL_FOOTPRINT_AVR_ADAPTER_BLOCKED_COVERAGE"
VERDICT_FAILED = "OBFULL_FOOTPRINT_AVR_ADAPTER_FAILED"
